### ISSUE TITLE
pcsctest hangs on Apple Silicon with Big Sur 11.2.3

### ISSUE THREAD

**Issue by yon** [LudovicRousseau/PCSC#101]
```
% /usr/bin/pcsctest 

MUSCLE PC/SC Lite Test Program

Testing SCardEstablishContext    : 
```

Same Yubikey tests successfully on a non-Apple Silicon MBP running same version of Big Sur.

USB interface is recognized:

```
USB 3.1 Bus:

  Host Controller Driver:	AppleT8103USBXHCI

Yubikey 4 OTP+U2F+CCID:

  Product ID:	0x0407
  Vendor ID:	0x1050
  Version:	4.45
  Speed:	Up to 12 Mb/s
  Manufacturer:	Yubico
  Location ID:	0x01100000 / 1
  Current Available (mA):	500
  Current Required (mA):	30
  Extra Operating Current (mA):	0
```

OTP and FIDO2/U2F test successfully at https://demo.yubico.com/

Can't utilize the smartcard interface for some reason. Also `ykman list --serials` also hangs.

**Comment by LudovicRousseau** [comment]
The problem is still present even after a reboot?

**Comment by yon** [comment]
No. Just rebooted and this problem is resolved. The Yubikey is now recognized. Thanks and sorry I missed that.
