### ISSUE TITLE
Unable to get details from NFC Card Reader ACR 122U PICC Interface. 

### ISSUE THREAD

**Issue by arpit-mehra** [LudovicRousseau/PCSC#107]
### Versions

* smart card reader driver name and version - ACR 122U PICC Interface
* pcsc-lite version
* the output of the command `/usr/sbin/pcscd --version`
1.8.23.

### Platform

* Operating system or GNU/Linux distribution name and version - RHEL 8
* Smart card middleware name and version 
* Smart card reader manufacturer name and reader model name
* Smart card name 

### Log

Then you shall generate a complete log (do not truncate it).

* If you need to enter the smart card PIN to reproduce the problem then
  consider changing your PIN before generating the logs as the PIN value
  will be included in the logs.
* Kill any running pcscd process
* (re)start pcscd exactly as described bellow:
```
sudo LIBCCID_ifdLogLevel=0x000F pcscd --foreground --debug --apdu --color | tee log.txt
```
[log.txt](https://github.com/LudovicRousseau/PCSC/files/6863283/log.txt)

* Stop pcscd (using Control-C) after the problem occured and send me the
  generated log.txt file

See also https://pcsclite.apdu.fr/#support

I am unable to read the NFC Card using NFC Card Reader ACR 122U PICC Interface. It always returns a `63 00` on Authenticate `ff 86 00 00 05 01 00 12 60 00`
Any idea what could be wrong with this ?

**Comment by LudovicRousseau** [comment]
It is not a problem at the PC/SC level.
Maybe you can get information from ACS reader documentation, or from the NFC card documentation.

See also https://ludovicrousseau.blogspot.com/2020/11/how-to-get-smart-card-support.html
