### ISSUE TITLE
Misleading references to /etc/reader.conf throughout the documentation

### ISSUE THREAD

**Issue by kirelagin** [LudovicRousseau/PCSC#115]
If I am reading the code correctly, there are two potential sources of configuration:

1. The file (or, actually, directory) optionally given as `-c` to the daemon.
2. The directory (or, actually, file) specified at build time as `--enable-confdir` and known in the code as `PCSCLITE_CONFIG_DIR`.

The former defaults to nothing and takes precedence over the latter; the latter defaults to `${sysconfdir}/reader.conf.d`.

At the same time, the documentation (and code comments) extensively mention `/etc/reader.conf` as the configuration file. Which, like, if I am not misreading the code, has no special significance and is never used, unless explicitly given as `-c` or `--enable-confdir` was somewhat weirdly and contrary to its intended use as a _directory_ set to `/etc/reader.conf`?

I guess, that’s first of all a clarification request: do I understand the actual logic of the code correctly? If yes, then, I guess, it would be great to update the documentation.

**Comment by LudovicRousseau** [comment]
You are right. It is confusing.
Historically only the file `/etc/reader.conf` was used. But it was difficult to use with 2 or more readers. So I moved to a directory. But the documentation was not updated.

I fixed the documentation. Please review.

**Comment by kirelagin** [comment]
Thanks for addressing this!

There are still a bunch of references remaining in documentation and user-facing messages:

* https://github.com/LudovicRousseau/PCSC/blob/e4afdbad265601170e4cfa2f304a513d863c3b77/configure.ac#L170 (maybe something like `reader.conf.d` files?)
* https://github.com/LudovicRousseau/PCSC/blob/e4afdbad265601170e4cfa2f304a513d863c3b77/doc/pcscd.8.in#L17 and some other locations in the same file (in other places you replaced it with `my_reader.conf`)
* I would also suggest renaming the man file from `reader.conf` to `reader.conf.d`, which seems to be a fairly standard thing to do for this kind of direcotry-based configuration (e.g. `man tmpfiles.d`).

**Comment by LudovicRousseau** [comment]
Better now?
I do not plan to rename the reader.conf.5 manpage. Non-USB readers are very rare now. I don't know if reader.conf files are really used.

**Comment by kirelagin** [comment]
Yes, I think now you have addressed all the remaining occurrences. Thanks again for handling this!

**Comment by kirelagin** [comment]
Ah, one last thing. You updated the man page for `pcscd` to say that `-c` takes a directory instead of a file, however the code still refers to it as a file:

* https://github.com/LudovicRousseau/PCSC/blob/68da917fb086e318eac2910877e2c87f9f49b370/src/pcscdaemon.c#L860
* https://github.com/LudovicRousseau/PCSC/blob/68da917fb086e318eac2910877e2c87f9f49b370/src/pcscdaemon.c#L339
* https://github.com/LudovicRousseau/PCSC/blob/68da917fb086e318eac2910877e2c87f9f49b370/src/pcscdaemon.c#L650 (this one is especially unclear, since, hmm, I’m not sure when the function fails – will it fail if only one of the files in the directory is wrong? how does the user know what exactly in the entire directory caused the problem/)

**Comment by LudovicRousseau** [comment]
I made some modifications in `pcscdaemon.c` and also improved pcscd.8 manpage.

**Comment by kirelagin** [comment]
I think it’s perfect now, thanks!
