### ISSUE TITLE
Comparsion of integer expressions of different signedness

### ISSUE THREAD

**Issue by EastHell** [LudovicRousseau/PCSC#120]
### Versions

pcsc-lite version:1.9.5

### Platform

Linux on android device

### Issue

I use make file.
Then I've got a compiler error.
Looks like rv is uint32_t and SCARD_F_INTERNAL_ERROR is long int and you shouldn't compare them either like here https://github.com/LudovicRousseau/PCSC/blob/b01f19fb9361a87cc4473dfb50ae73b0a6871671/src/winscard_svc.c line 441

### Log

![telegram-cloud-photo-size-2-5217971427817403885-y](https://user-images.githubusercontent.com/28960974/154234143-81bcaa15-7e50-43b5-bf73-c5739570338f.jpg)

**Comment by LudovicRousseau** [comment]
Thanks
