### ISSUE TITLE
Alcor AU9540 Not Recognizing New PIV

### ISSUE THREAD

**Issue by bnordgren** [LudovicRousseau/PCSC#122]
### Versions

* smart card reader driver name and version: pcsc-lite-ccid-1.5.0-1.fc35.x86_64
* pcsc-lite version: pcsc-lite-1.9.5-1.fc35.x86_64
* the output of the command `/usr/sbin/pcscd --version`
```
pcsc-lite version 1.9.5.
Copyright (C) 1999-2002 by David Corcoran <corcoran@musclecard.com>.
Copyright (C) 2001-2018 by Ludovic Rousseau <ludovic.rousseau@free.fr>.
Copyright (C) 2003-2004 by Damien Sauveron <sauveron@labri.fr>.
Report bugs to <pcsclite-muscle@lists.infradead.org>.
Enabled features: Linux x86_64-redhat-linux-gnu libsystemd serial usb libudev usbdropdir=/usr/lib64/pcsc/drivers ipcdir=/run/pcscd filter configdir=/etc/reader.conf.d

```

### Platform

* Fedora 35 Silverblue
* pcsc-lite-1.9.5
* Alcor Micro Corp. AU9540 Smartcard Reader 
* Smartcard:
```
        Oberthur Technologies ID-One PIV/CIV on V8 Device (eID)
	https://csrc.nist.gov/csrc/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp2986.pdf

```

### Issue

* What do you do? : Insert Card, run `pcsc_scan` and `pkcs11-tool -L`
* What result do you expect? See that card is inserted
* What result do you get instead? Card reader reported empty
* Additional information: The reader stopped recognizing my PIV card when I got a new card due to the old one expiring. The card works in other computers and other readers attached to this computer. There is a Windows VM on this same machine which accesses this card reader (when it's on) via USB Passthrough. It failed to recognize my new card until a specific Alcor driver was installed (until now, it was using the generic Microsoft CCID driver.) If I run the VM and allow Windows to access the card reader using the Alcor specific driver, then turn the VM off and start pcscd again, my new card is recognized. The new card continues to be recognized after I reboot. However, if I power off and power back on, the linux side does not recognize the card until Windows can apply the Alcor-specific driver to it.

### Log

* pcscd logfile output: [scan_and_list.txt](https://github.com/LudovicRousseau/PCSC/files/8326199/scan_and_list.txt)
* client console output: [clients.txt](https://github.com/LudovicRousseau/PCSC/files/8326198/clients.txt)

**Comment by bnordgren** [comment]
That says the reader or the BIOS decides to power off the card without intervention of the CCID driver, and the Ubuntu issue from 2014 seems to indicate that this is an infinite loop? Grepping for power in the log doesn't seem to indicate that there's a loop going on. It does say something about "CCID_Receive Hardware error". 

Is this the same thing as the problem that landed it on the unsupported list? 

Is there anything helpful that I can dump out from the reader before and after Windows configures it to work?

**Comment by LudovicRousseau** [comment]
You may have a different problem.

Unless you have a budget so I can work on adding support of your reader I can't help.
I suggest to use another reader instead.

**Comment by LudovicRousseau** [comment]
This reader is unsupported.
Closing.

**Comment by LudovicRousseau** [comment]
Please see https://ludovicrousseau.blogspot.com/2022/12/alcormicro-au9560-reader-and-fast-smart.html

**Comment by LudovicRousseau** [comment]
CCID 1.5.2 is now available.
https://ludovicrousseau.blogspot.com/2023/01/new-version-of-libccid-152.html

It will be included in the next Debian version (Debian 12) and in Ubuntu 23.04. I have no visibility for the other GNU/Linux distributions.
