### ISSUE TITLE
Option to change the pcscd listen socket

### ISSUE THREAD

**Issue by inorton** [LudovicRousseau/PCSC#123]
Hi, I have a situation where I'd quite like to run several pcscd at the same time (complex test setup).  We can currently change the client application socket used by setting PCSCLITE_CSOCK_NAME.  It would be very useful for me to be able to make pcscd use the same variable to listen on a different socket.

**Comment by LudovicRousseau** [comment]
It should be easy to do.
I don't think this feature would have a lot of users. So I may not include it.

**Comment by inorton** [comment]
If I get some time, I'll make a pull request with this in.

**Comment by LudovicRousseau** [comment]
great
