### ISSUE TITLE
build failure on debian 10?

### ISSUE THREAD

**Issue by inorton** [LudovicRousseau/PCSC#124]
Hi, trying to build locally, I do:

```
./bootstrap
./configure
make
```

bootstrap and configure succeed without errors or warnings, but make fails part way in with:
```
  LEX      configfile.c
  CC       pcscd-configfile.o
gcc: error: ./configfile.c: No such file or directory
gcc: fatal error: no input files

```

**Comment by LudovicRousseau** [comment]
It works for me.
Check if the file `configfile.c` has been created.
Check you have `flex` installed.

**Comment by inorton** [comment]
Thanks, missing flex is the problem,  should bootstrap or configure catch that?
