### ISSUE TITLE
PCSC_scan hangs

### ISSUE THREAD

**Issue by beruysaliz** [LudovicRousseau/PCSC#141]
### Versions

* smart card reader driver name and version
* pcsc-lite version
* the output of the command `/usr/sbin/pcscd --version`
![Screenshot from 2022-06-27 12-55-47](https://user-images.githubusercontent.com/19360447/175927266-462522c6-1d93-48f0-9fc0-8670ad36ff5b.png)

### Platform

* Operating system or GNU/Linux distribution name and version
* ubuntu 18.04.5
* Smart card middleware name and version
* Smart card reader manufacturer name and reader model name
* Gemalto (was Gemplus) GemPC Key SmartCard Reader
* Smart card name
* sysmoUSIM-SJS1

### Issue

* What do you do?
* try to scan reader.
* What result do you expect?
* want to see usim.
* What result do you get instead?
![Screenshot from 2022-06-27 12-47-46](https://user-images.githubusercontent.com/19360447/175926881-1d361942-2725-4907-ad7f-cc75cc9f8abb.png)

### Log

Then you shall generate a complete log (do not truncate it).

* If you need to enter the smart card PIN to reproduce the problem then
  consider changing your PIN before generating the logs as the PIN value
  will be included in the logs.
* Kill any running pcscd process
* (re)start pcscd exactly as described bellow:
```
sudo LIBCCID_ifdLogLevel=0x000F pcscd --foreground --debug --apdu --color | tee log.txt
```
* Stop pcscd (using Control-C) after the problem occured and send me the
  generated log.txt file
![Screenshot from 2022-06-27 12-54-39](https://user-images.githubusercontent.com/19360447/175927190-9ba4b7a0-e4a0-47ab-b99f-4189c09adc68.png)

See also https://pcsclite.apdu.fr/#support

**Comment by LudovicRousseau** [comment]
You have rebuilt pcsc-lite yourself.
By default it uses `/usr/local/lib/pcsc/` to search for reader drivers. But you have NO driver installed in this directory.

You have 2 versions of pcscd installed on your system:

- /usr/sbin/pcscd (from the Ubuntu package)
- /usr/local/sbin/pcscd (local built)

This is a bad idea.

A good idea is to remove your "custom" pcsc-lite and use only Ubuntu packages.
You may also upgrade to Ubuntu 22.04
