### ISSUE TITLE
can add phoenix reader support?

### ISSUE THREAD

**Issue by canghaiwuhen** [LudovicRousseau/PCSC#142]
phoenix reader 
https://circuitsarchive.org/circuits/smartcard/smartcard-pc-serial-reader-writer-phoenix
https://www.ladyada.net/make/simreader/faq.html
alse can use Prolific PL-2303
https://osmocom.org/projects/cellular-infrastructure/wiki/MagicSIM

use openct can found reader, but thhe second one is not recognized if multiple card readers are used.

openct demo:
https://timesinker.blogspot.com/2016/04/using-cheap-sim-card-readers.html

openct-phoenix driver
https://sourceforge.net/projects/openct-phoenix/files/openct-phoenix

**Comment by canghaiwuhen** [comment]
Bus 003 Device 006: ID 067b:2303 Prolific Technology, Inc. PL2303 Serial Port

**Comment by LudovicRousseau** [comment]
https://ccid.apdu.fr/#CCID_compliant

**Comment by LudovicRousseau** [comment]
To be followed in https://github.com/LudovicRousseau/CCID/issues/99
