### ISSUE TITLE
pcscd or ykman hangs when running ykman info with Yubikey 5

### ISSUE THREAD

**Issue by wmaroulis** [LudovicRousseau/PCSC#145]
### Versions

# /usr/sbin/pcscd --version
pcsc-lite version 1.9.5.
Copyright (C) 1999-2002 by David Corcoran <corcoran@musclecard.com>.
Copyright (C) 2001-2018 by Ludovic Rousseau <ludovic.rousseau@free.fr>.
Copyright (C) 2003-2004 by Damien Sauveron <sauveron@labri.fr>.
Report bugs to <pcsclite-muscle@lists.infradead.org>.
Enabled features: Linux x86_64-redhat-linux-gnu libsystemd serial usb libudev usbdropdir=/usr/lib64/pcsc/drivers ipcdir=/run/pcscd filter configdir=/etc/reader.conf.d

### Platform

# uname -a
Linux localhost.localdomain 5.15.0-0.30.20.el8uek.x86_64 #2 SMP Sun Jul 10 12:13:30 PDT 2022 x86_64 x86_64 x86_64 GNU/Linux

# lsusb
Bus 001 Device 002: ID 1050:0407 Yubico.com Yubikey 4/5 OTP+U2F+CCID
Bus 001 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub

### Issue

* What do you do?
Trying to run "poetry run ykman info" from yubikey-manager.

* What result do you expect?
results

* What result do you get instead?
Both ykman and pcscd hang

pcscd - appears to hang during "winscard_svc.c:362:ContextThread() Received command: CMD_GET_READERS_STATE from client 14"
from log - see below

strace from ykman and pcscd - show "poll" calls at the time of the hang

ykman_strace - output at time of hang

3139  1658695926.023272 sendto(3, "\0\0\0\0\22\0\0\0", 8, MSG_NOSIGNAL, NULL, 0) = 8
3139  1658695926.023318 poll([{fd=3, events=POLLIN}], 1, -1) = 1 ([{fd=3, revents=POLLIN}])
3139  1658695926.023404 read(3, "Yubico Yubikey 4 OTP+U2F+CCID 00"..., 8832) = 2944
3139  1658695926.023445 poll([{fd=3, events=POLLIN}], 1, -1

pcscd strace - out at time of hang

3144  1658695926.023341 write(1, "\33[36m00000242\33[0m [1401004573632"..., 126) = 126
3144  1658695926.023353 poll([{fd=14, events=POLLOUT}], 1, -1) = 1 ([{fd=14, revents=POLLOUT}])
3144  1658695926.023364 sendto(14, "Yubico Yubikey 4 OTP+U2F+CCID 00"..., 2944, MSG_NOSIGNAL, NULL, 0) = 2944
3144  1658695926.023383 poll([{fd=14, events=POLLIN}], 1, -1

### Log

00000000 debuglog.c:297:DebugLogSetLevel() debug level=debug
00000110 debuglog.c:318:DebugLogSetCategory() Debug options: APDU
00000047 [140100540411392] pcscdaemon.c:356:main() Force colored logs
00000801 [140100540411392] configfile.l:370:DBGetReaderList() Parsing conf file: /usr/local/etc/reader.conf.d
00000103 [140100540411392] pcscdaemon.c:666:main() pcsc-lite 1.9.8 daemon ready.
00025786 [140100540411392] hotplug_libudev.c:302:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0001, path: /dev/bus/usb/001/001
00002908 [140100540411392] hotplug_libudev.c:302:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0001, path: /dev/bus/usb/001/001
00003221 [140100540411392] hotplug_libudev.c:302:get_driver() Looking for a driver for VID: 0x1050, PID: 0x0407, path: /dev/bus/usb/001/002
00000056 [140100540411392] hotplug_libudev.c:421:HPAddDevice() Adding USB device: Yubico Yubikey 4 OTP+U2F+CCID
00000489 [140100540411392] readerfactory.c:1094:RFInitializeReader() Attempting startup of Yubico Yubikey 4 OTP+U2F+CCID 00 00 using /usr/local/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Linux/libccid.so
00001649 [140100540411392] readerfactory.c:968:RFBindFunctions() Loading IFD Handler 3.0
00000080 [140100540411392] ifdhandler.c:1961:init_driver() Driver version: 1.4.29
00001075 [140100540411392] ifdhandler.c:1978:init_driver() LogLevel: 0x0003
00000052 [140100540411392] ifdhandler.c:1989:init_driver() DriverOptions: 0x0000
00000132 [140100540411392] ifdhandler.c:2002:init_driver() LogLevel from LIBCCID_ifdLogLevel: 0x000F
00000047 [140100540411392] ifdhandler.c:110:CreateChannelByNameOrChannel() Lun: 0, device: usb:1050/0407:libudev:0:/dev/bus/usb/001/002
00000044 [140100540411392] ccid_usb.c:237:OpenUSBByName() Reader index: 0, Device: usb:1050/0407:libudev:0:/dev/bus/usb/001/002
00000051 [140100540411392] ccid_usb.c:269:OpenUSBByName() interface_number: 0
00000048 [140100540411392] ccid_usb.c:270:OpenUSBByName() usb bus/device: 1/2
00000047 [140100540411392] ccid_usb.c:302:OpenUSBByName() Using: /usr/lib64/pcsc/drivers/ifd-ccid.bundle/Contents/Info.plist
00000936 [140100540411392] ccid_usb.c:320:OpenUSBByName() ifdManufacturerString: Ludovic Rousseau (ludovic.rousseau@free.fr)
00000047 [140100540411392] ccid_usb.c:321:OpenUSBByName() ifdProductString: Generic CCID driver
00000044 [140100540411392] ccid_usb.c:322:OpenUSBByName() Copyright: This driver is protected by terms of the GNU Lesser General Public License version 2.1, or (at your option) any later version.
00022066 [140100540411392] ccid_usb.c:406:OpenUSBByName() Try device: 1/2
00000055 [140100540411392] ccid_usb.c:416:OpenUSBByName() vid/pid : 1050/0407
00000047 [140100540411392] ccid_usb.c:483:OpenUSBByName() Checking device: 1/2
00000045 [140100540411392] ccid_usb.c:554:OpenUSBByName() Trying to open USB bus/device: 1/2
00000471 [140100540411392] ccid_usb.c:634:OpenUSBByName() Found interface 2 but expecting 0
00000051 [140100540411392] ccid_usb.c:636:OpenUSBByName() Wrong interface for USB device 1/2. Checking next one.
00000358 [140100540411392] ccid_usb.c:189:close_libusb_if_needed() libusb_exit
00000605 [140100540411392] ccid_usb.c:789:OpenUSBByName() Device not found?
00000045 [140100540411392] ifdhandler.c:150:CreateChannelByNameOrChannel() failed
00000041 [140100540411392] readerfactory.c:1135:RFInitializeReader() Open Port 0x200000 Failed (usb:1050/0407:libudev:0:/dev/bus/usb/001/002)
00000041 [140100540411392] readerfactory.c:378:RFAddReader() Yubico Yubikey 4 OTP+U2F+CCID init failed.
00000039 [140100540411392] readerfactory.c:628:RFRemoveReader() UnrefReader() count was: 1
00000048 [140100540411392] readerfactory.c:1148:RFUnInitializeReader() Attempting shutdown of Yubico Yubikey 4 OTP+U2F+CCID 00 00.
00000038 [140100540411392] readerfactory.c:1005:RFUnloadReader() Unloading reader driver.
00002821 [140100540411392] hotplug_libudev.c:302:get_driver() Looking for a driver for VID: 0x1050, PID: 0x0407, path: /dev/bus/usb/001/002
00000048 [140100540411392] hotplug_libudev.c:421:HPAddDevice() Adding USB device: Yubico Yubikey 4 OTP+U2F+CCID
00000398 [140100540411392] readerfactory.c:1094:RFInitializeReader() Attempting startup of Yubico Yubikey 4 OTP+U2F+CCID 00 00 using /usr/local/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Linux/libccid.so
00001297 [140100540411392] readerfactory.c:968:RFBindFunctions() Loading IFD Handler 3.0
00000056 [140100540411392] ifdhandler.c:1961:init_driver() Driver version: 1.4.29
00000865 [140100540411392] ifdhandler.c:1978:init_driver() LogLevel: 0x0003
00000048 [140100540411392] ifdhandler.c:1989:init_driver() DriverOptions: 0x0000
00000122 [140100540411392] ifdhandler.c:2002:init_driver() LogLevel from LIBCCID_ifdLogLevel: 0x000F
00000040 [140100540411392] ifdhandler.c:110:CreateChannelByNameOrChannel() Lun: 0, device: usb:1050/0407:libudev:1:/dev/bus/usb/001/002
00000042 [140100540411392] ccid_usb.c:237:OpenUSBByName() Reader index: 0, Device: usb:1050/0407:libudev:1:/dev/bus/usb/001/002
00000042 [140100540411392] ccid_usb.c:269:OpenUSBByName() interface_number: 1
00000038 [140100540411392] ccid_usb.c:270:OpenUSBByName() usb bus/device: 1/2
00000038 [140100540411392] ccid_usb.c:302:OpenUSBByName() Using: /usr/lib64/pcsc/drivers/ifd-ccid.bundle/Contents/Info.plist
00000872 [140100540411392] ccid_usb.c:320:OpenUSBByName() ifdManufacturerString: Ludovic Rousseau (ludovic.rousseau@free.fr)
00000045 [140100540411392] ccid_usb.c:321:OpenUSBByName() ifdProductString: Generic CCID driver
00000039 [140100540411392] ccid_usb.c:322:OpenUSBByName() Copyright: This driver is protected by terms of the GNU Lesser General Public License version 2.1, or (at your option) any later version.
00022570 [140100540411392] ccid_usb.c:406:OpenUSBByName() Try device: 1/2
00000053 [140100540411392] ccid_usb.c:416:OpenUSBByName() vid/pid : 1050/0407
00000056 [140100540411392] ccid_usb.c:483:OpenUSBByName() Checking device: 1/2
00000050 [140100540411392] ccid_usb.c:554:OpenUSBByName() Trying to open USB bus/device: 1/2
00000405 [140100540411392] ccid_usb.c:634:OpenUSBByName() Found interface 2 but expecting 1
00000043 [140100540411392] ccid_usb.c:636:OpenUSBByName() Wrong interface for USB device 1/2. Checking next one.
00000362 [140100540411392] ccid_usb.c:189:close_libusb_if_needed() libusb_exit
00000556 [140100540411392] ccid_usb.c:789:OpenUSBByName() Device not found?
00000044 [140100540411392] ifdhandler.c:150:CreateChannelByNameOrChannel() failed
00000037 [140100540411392] readerfactory.c:1135:RFInitializeReader() Open Port 0x200000 Failed (usb:1050/0407:libudev:1:/dev/bus/usb/001/002)
00000035 [140100540411392] readerfactory.c:378:RFAddReader() Yubico Yubikey 4 OTP+U2F+CCID init failed.
00000047 [140100540411392] readerfactory.c:628:RFRemoveReader() UnrefReader() count was: 1
00000038 [140100540411392] readerfactory.c:1148:RFUnInitializeReader() Attempting shutdown of Yubico Yubikey 4 OTP+U2F+CCID 00 00.
00000036 [140100540411392] readerfactory.c:1005:RFUnloadReader() Unloading reader driver.
00002740 [140100540411392] hotplug_libudev.c:302:get_driver() Looking for a driver for VID: 0x1050, PID: 0x0407, path: /dev/bus/usb/001/002
00000046 [140100540411392] hotplug_libudev.c:421:HPAddDevice() Adding USB device: Yubico Yubikey 4 OTP+U2F+CCID
00000415 [140100540411392] readerfactory.c:1094:RFInitializeReader() Attempting startup of Yubico Yubikey 4 OTP+U2F+CCID 00 00 using /usr/local/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Linux/libccid.so
00001260 [140100540411392] readerfactory.c:968:RFBindFunctions() Loading IFD Handler 3.0
00000054 [140100540411392] ifdhandler.c:1961:init_driver() Driver version: 1.4.29
00000870 [140100540411392] ifdhandler.c:1978:init_driver() LogLevel: 0x0003
00000050 [140100540411392] ifdhandler.c:1989:init_driver() DriverOptions: 0x0000
00000133 [140100540411392] ifdhandler.c:2002:init_driver() LogLevel from LIBCCID_ifdLogLevel: 0x000F
00000039 [140100540411392] ifdhandler.c:110:CreateChannelByNameOrChannel() Lun: 0, device: usb:1050/0407:libudev:2:/dev/bus/usb/001/002
00000037 [140100540411392] ccid_usb.c:237:OpenUSBByName() Reader index: 0, Device: usb:1050/0407:libudev:2:/dev/bus/usb/001/002
00000038 [140100540411392] ccid_usb.c:269:OpenUSBByName() interface_number: 2
00000037 [140100540411392] ccid_usb.c:270:OpenUSBByName() usb bus/device: 1/2
00000037 [140100540411392] ccid_usb.c:302:OpenUSBByName() Using: /usr/lib64/pcsc/drivers/ifd-ccid.bundle/Contents/Info.plist
00000837 [140100540411392] ccid_usb.c:320:OpenUSBByName() ifdManufacturerString: Ludovic Rousseau (ludovic.rousseau@free.fr)
00000039 [140100540411392] ccid_usb.c:321:OpenUSBByName() ifdProductString: Generic CCID driver
00000036 [140100540411392] ccid_usb.c:322:OpenUSBByName() Copyright: This driver is protected by terms of the GNU Lesser General Public License version 2.1, or (at your option) any later version.
00020935 [140100540411392] ccid_usb.c:406:OpenUSBByName() Try device: 1/2
00000051 [140100540411392] ccid_usb.c:416:OpenUSBByName() vid/pid : 1050/0407
00000045 [140100540411392] ccid_usb.c:483:OpenUSBByName() Checking device: 1/2
00000045 [140100540411392] ccid_usb.c:554:OpenUSBByName() Trying to open USB bus/device: 1/2
00000464 [140100540411392] ccid_usb.c:656:OpenUSBByName() Found Vendor/Product: 1050/0407 (Yubico Yubikey 4 OTP+U2F+CCID)
00000048 [140100540411392] ccid_usb.c:658:OpenUSBByName() Using USB bus/device: 1/2
00000051 [140100540411392] ccid_usb.c:717:OpenUSBByName() bNumDataRatesSupported is 0
00028691 [140100540411392] ccid_usb.c:1296:InterruptRead() before (0)
00103562 [140100540411392] ccid_usb.c:1342:InterruptRead() after (0) (2)
00000409 [140100540411392] -> 000000 65 00 00 00 00 00 00 00 00 00
00013226 [140100540411392] <- 000000 81 00 00 00 00 00 00 00 00 00
00000335 [140100540411392] -> 000000 65 00 00 00 00 00 01 00 00 00
00009943 [140100540411392] <- 000000 81 00 00 00 00 00 01 00 00 00
00000248 [140100540411392] ifdhandler.c:381:IFDHGetCapabilities() tag: 0xFB3, usb:1050/0407:libudev:2:/dev/bus/usb/001/002 (lun: 0)
00000285 [140100540411392] readerfactory.c:398:RFAddReader() Using the reader polling thread
00000257 [140100540411392] ifdhandler.c:1821:IFDHICCPresence() usb:1050/0407:libudev:2:/dev/bus/usb/001/002 (lun: 0)
00000299 [140100540411392] -> 000000 65 00 00 00 00 00 02 00 00 00
00010103 [140100540411392] <- 000000 81 00 00 00 00 00 02 00 00 00
00000262 [140100540411392] ifdhandler.c:1942:IFDHICCPresence() Card present
00000765 [140100540411392] ifdhandler.c:381:IFDHGetCapabilities() tag: 0xFAE, usb:1050/0407:libudev:2:/dev/bus/usb/001/002 (lun: 0)
00000060 [140100540411392] ifdhandler.c:476:IFDHGetCapabilities() Reader supports 1 slot(s)
00000122 [140100474148608] ifdhandler.c:1821:IFDHICCPresence() usb:1050/0407:libudev:2:/dev/bus/usb/001/002 (lun: 0)
00000052 [140100474148608] -> 000000 65 00 00 00 00 00 03 00 00 00
00000148 [140100540411392] readerfactory.c:1436:RFWaitForReaderInit() Waiting init for reader: Yubico Yubikey 4 OTP+U2F+CCID 00 00
00008500 [140100474148608] <- 000000 81 00 00 00 00 00 03 00 00 00
00000035 [140100474148608] ifdhandler.c:1942:IFDHICCPresence() Card present
00000032 [140100474148608] ifdhandler.c:1821:IFDHICCPresence() usb:1050/0407:libudev:2:/dev/bus/usb/001/002 (lun: 0)
00000017 [140100474148608] -> 000000 65 00 00 00 00 00 04 00 00 00
00001793 [140100540411392] readerfactory.c:1436:RFWaitForReaderInit() Waiting init for reader: Yubico Yubikey 4 OTP+U2F+CCID 00 00
00009793 [140100474148608] <- 000000 81 00 00 00 00 00 04 00 00 00
00000053 [140100474148608] ifdhandler.c:1942:IFDHICCPresence() Card present
00000021 [140100474148608] ifdhandler.c:1154:IFDHPowerICC() action: PowerUp, usb:1050/0407:libudev:2:/dev/bus/usb/001/002 (lun: 0)
00000042 [140100474148608] -> 000000 62 00 00 00 00 00 05 00 00 00
00001785 [140100540411392] readerfactory.c:1436:RFWaitForReaderInit() Waiting init for reader: Yubico Yubikey 4 OTP+U2F+CCID 00 00
00008592 [140100474148608] <- 000000 80 17 00 00 00 00 05 00 00 00 3B FD 13 00 00 81 31 FE 15 80 73 C0 21 C0 57 59 75 62 69 4B 65 79 40
00000025 [140100474148608] eventhandler.c:289:EHStatusHandlerThread() powerState: POWER_STATE_POWERED
00000016 [140100474148608] Card ATR: 3B FD 13 00 00 81 31 FE 15 80 73 C0 21 C0 57 59 75 62 69 4B 65 79 40
00000017 [140100474148608] ifdhandler.c:1821:IFDHICCPresence() usb:1050/0407:libudev:2:/dev/bus/usb/001/002 (lun: 0)
00000016 [140100474148608] -> 000000 65 00 00 00 00 00 06 00 00 00
00010674 [140100474148608] <- 000000 81 00 00 00 00 00 06 00 00 00
00000028 [140100474148608] ifdhandler.c:1942:IFDHICCPresence() Card present
00000022 [140100474148608] ifdhandler.c:310:IFDHPolling() usb:1050/0407:libudev:2:/dev/bus/usb/001/002 (lun: 0) 5000 ms
00000020 [140100474148608] ccid_usb.c:1296:InterruptRead() before (0)
05021024 [140100474148608] ccid_usb.c:1342:InterruptRead() after (0) (2)
00000045 [140100474148608] ifdhandler.c:1821:IFDHICCPresence() usb:1050/0407:libudev:2:/dev/bus/usb/001/002 (lun: 0)
00000032 [140100474148608] -> 000000 65 00 00 00 00 00 07 00 00 00
00027915 [140100474148608] <- 000000 81 00 00 00 00 00 07 00 00 00
00000034 [140100474148608] ifdhandler.c:1942:IFDHICCPresence() Card present
00000027 [140100474148608] ifdhandler.c:1154:IFDHPowerICC() action: PowerDown, usb:1050/0407:libudev:2:/dev/bus/usb/001/002 (lun: 0)
00000025 [140100474148608] -> 000000 63 00 00 00 00 00 08 00 00 00
00010747 [140100474148608] <- 000000 81 00 00 00 00 00 08 02 00 00
00000033 [140100474148608] eventhandler.c:482:EHStatusHandlerThread() powerState: POWER_STATE_UNPOWERED
00000024 [140100474148608] ifdhandler.c:1821:IFDHICCPresence() usb:1050/0407:libudev:2:/dev/bus/usb/001/002 (lun: 0)
00000023 [140100474148608] -> 000000 65 00 00 00 00 00 09 00 00 00
00009538 [140100474148608] <- 000000 81 00 00 00 00 00 09 00 00 00
00000027 [140100474148608] ifdhandler.c:1942:IFDHICCPresence() Card present
00000020 [140100474148608] ifdhandler.c:310:IFDHPolling() usb:1050/0407:libudev:2:/dev/bus/usb/001/002 (lun: 0) 600000 ms
00000017 [140100474148608] ccid_usb.c:1296:InterruptRead() before (0)
05003184 [140100540411392] winscard_msg_srv.c:256:ProcessEventsServer() Common channel packet arrival
00000193 [140100540411392] winscard_msg_srv.c:268:ProcessEventsServer() ProcessCommonChannelRequest detects: 14
00000071 [140100540411392] pcscdaemon.c:133:SVCServiceRunLoop() A new context thread creation is requested: 14
00000370 [140100457363200] winscard_svc.c:340:ContextThread() Authorized PC/SC client
00000022 [140100457363200] winscard_svc.c:344:ContextThread() Thread is started: dwClientID=14, threadContext @0x255fac0
00000042 [140100457363200] winscard_svc.c:362:ContextThread() Received command: CMD_VERSION from client 14
00000037 [140100457363200] winscard_svc.c:374:ContextThread() Client is protocol version 4:4
00000012 [140100457363200] winscard_svc.c:396:ContextThread() CMD_VERSION rv=0x0 for client 14
00000312 [140100457363200] winscard_svc.c:362:ContextThread() Received command: ESTABLISH_CONTEXT from client 14
00000138 [140100457363200] winscard.c:215:SCardEstablishContext() Establishing Context: 0x748B8501
00000012 [140100457363200] winscard_svc.c:465:ContextThread() ESTABLISH_CONTEXT rv=0x0 for client 14
00000242 [140100457363200] winscard_svc.c:362:ContextThread() Received command: CMD_GET_READERS_STATE from client 14
99999999 [140100457363200] winscard_svc.c:354:ContextThread() Client die: 14
00000107 [140100457363200] winscard.c:229:SCardReleaseContext() Releasing Context: 0x748B8501
00000118 [140100457363200] winscard_svc.c:1073:MSGCleanupClient() Thread is stopping: dwClientID=14, threadContext @0x255fac0
00000025 [140100457363200] winscard_svc.c:1079:MSGCleanupClient() Freeing SCONTEXT @0x255fac0
07013356 [140100495361792] pcscdaemon.c:193:signal_thread() Received signal: 2
00000117 [140100495361792] pcscdaemon.c:227:signal_thread() Preparing for suicide
00004773 [140100540411392] hotplug_libudev.c:709:HPStopHotPluggables() Hotplug stopped

**Comment by LudovicRousseau** [comment]
Do you use a virtual environment like flatpak or similar?

**Comment by wmaroulis** [comment]
Yes - I am running the Oracle Linux image from above (where I have built PCSC, yubikey, etc) in VirtualBox - version 6.1.34 r150636 (Qt5.6.2)

**Comment by LudovicRousseau** [comment]
I ask because from your 2 strace traces I get:
- the client is trying to read 8832 bytes
- the server (pcscd) is writting 2944 bytes

2944 = 184 * 16 (support of 16 readers _i.e._ the default value)
8832 = 184 * 48 (support of 48 readers)

It looks like the client is using a libpcsclite compiled with Fedora patches but the server does not have the Fedora patches.
See https://ludovicrousseau.blogspot.com/2022/02/fedora-flatpak-and-pcsc-lite.html for more details.

You are mixing 2 different builds of pcsc-lite.
If both the client and server run inside VirtualBox and comes from the same distribution it should not be a problem. But your setup is not correct somewhere.

**Comment by wmaroulis** [comment]
Thanks for the info - that was it!

I updated PCSC/src/PCSC/pcsclite.h.in and changed the PCSCLITE_MAX_READERS_CONTEXTS from 16 to 48 then re-made pcscd vi make clean, make, and make install - re-ran the test and it worked.

strace from pcscd

7353  1658798705.535363 sendto(14, "Yubico Yubikey 4 OTP+U2F+CCID 00"..., 8832, MSG_NOSIGNAL, NULL, 0) = 8832

Thanks again!
