### ISSUE TITLE
Error parsing Info.plist file

### ISSUE THREAD

**Issue by thotheolh** [LudovicRousseau/PCSC#15]
I attempted to add a new USB CCID device (a new Feitian USB CCID product called K9) into the Info.plist and restarted the pcscd but it seems to show that there is an error parsing the Info.plist.

I am running the setup on an ARM Linux.

I ran a 'sudo pcscd -d -f' which displayed the parsing error. The Info.plist contained in the ZIP file contains the 'Feitian CCID K9' entry with the Vendor ID of 096E and Product ID of 0856.

[parse-err.zip](https://github.com/LudovicRousseau/PCSC/files/729886/parse-err.zip)

**Comment by LudovicRousseau** [comment]
Do not edit the ``Info.plist`` by hand.
Follow https://pcsclite.alioth.debian.org/ccid.html#CCID_compliant to get a new reader added to the list.
