### ISSUE TITLE
configure: error: cannot find required auxiliary files: ltmain.sh config.guess config.sub

### ISSUE THREAD

**Issue by Vviotti** [LudovicRousseau/PCSC#163]
### Versions

* ifdokccid 4.3.3-3-a973c36ed296
* pcsc-lite 2.0.0
* N/A

### Platform

* Pop!_OS 22.04 LTS
* OmniKey 3121

### Issue

Installation issue

Apologies for such a basic problem but I'm still new in Linux and have not found a solution online.

* What do you do?

I tried installing OmniKey driver, but error on script indicated "PCSC-Lite" missing
Downloaded and extracted "pcsc-lite-2.0.0.tar.bz2"
Reading from "INSTALL" I performed the command "sudo ./configure && make && make install" in terminal shell on the directory of extracted folder

* What result do you expect?
Installation to be performed

* What result do you get instead?

configure: error: cannot find required auxiliary files: ltmain.sh config.guess config.sub

I'm grateful for any support given.

**Comment by LudovicRousseau** [comment]
The PCSC project does NOT provide a `INSTALL` file.

Where did you get "pcsc-lite-2.0.0.tar.bz2" archive?

The latest version is 2.0.1. See https://pcsclite.apdu.fr/files/

**Comment by Vviotti** [comment]
The Install file i mentioned on my initial comment regarded the install.txt

It took me a while to understand why exactly I had downloaded version 2.0.0, best explanation I can think is I miss clicked and when the notification for download concluded came about I did not questioned.

version  2.0.1 worked marvelously. Thank you for the assistance.

**Comment by Vviotti** [comment]
The Install file i mentioned on my initial comment regarded the install.txt

It took me a while to understand why exactly I had downloaded version 2.0.0, best explanation I can think is I miss clicked and when the notification for download concluded came about I did not questioned.

version 2.0.1 worked marvelously. Thank you for the assistance.
