### ISSUE TITLE
pcsc-spy triggers crash dialogue on MacOS X when hitting `ctrl-c`

### ISSUE THREAD

**Issue by ajmas** [LudovicRousseau/PCSC#177]
### Versions

* smart card reader driver name and version
* pcsc-lite version: 2.1.0 (provided by home brew): 
* the output of the command `/usr/sbin/pcscd --version`:

```
pcsc-lite version 2.1.0.
Copyright (C) 1999-2002 by David Corcoran <corcoran@musclecard.com>.
Copyright (C) 2001-2022 by Ludovic Rousseau <ludovic.rousseau@free.fr>.
Copyright (C) 2003-2004 by Damien Sauveron <sauveron@labri.fr>.
Report bugs to <pcsclite-muscle@lists.infradead.org>.
Enabled features: MacOS x86_64-apple-darwin23.4.0 serial usb usbdropdir=/usr/local/Cellar/pcsc-lite/2.1.0/lib/pcsc/drivers ipcdir=/run/pcscd filter configdir=/usr/local/etc/reader.conf.d
MAX_READERNAME: 128, PCSCLITE_MAX_READERS_CONTEXTS: 16
```

### Platform

* Operating system or GNU/Linux distribution name and version: macOS 14.4.1
* Smart card middleware name and version n/a
* Smart card reader manufacturer name and reader model name n/a
* Smart card name n/a

### Issue

* What do you do? 
  * Launched `pcsc-spy` via: `/usr/local/opt/pcsc-lite/bin/pcsc-spy` 
  * Hit ctrl-c
* What result do you expect? CLI to exit without issue
* What result do you get instead? Crash dialogue

This happens irrespective of card read being connected or not.

### Log

Then you shall generate a complete log (do not truncate it).

[pcsc-spy crash log.txt](https://github.com/LudovicRousseau/PCSC/files/15169665/pcsc-spy.crash.log.txt)

**Comment by ajmas** [comment]
I was getting this every time I ran the command, but now as I try to analyse the cause I can't reproduce it?

I'll reopen the ticket if I have more data to help in the analysis.

**Comment by LudovicRousseau** [comment]
pcsc-lite is not supported on macOS.
