### ISSUE TITLE
pscsd '/run' path ignores configure setting

### ISSUE THREAD

**Issue by ajmas** [LudovicRousseau/PCSC#178]
### Versions

* smart card reader driver name and version n/a
* pcsc-lite version 2.0.3
* the output of the command `/usr/sbin/pcscd --version`

### Platform

* Operating system or GNU/Linux distribution name and version macOS 14.4.1
* Smart card middleware name and version n/a
* Smart card reader manufacturer name and reader model name n/a
* Smart card name n/a

### Issue

Have installed pcsc-lite via `homebrew` and when I try running pcsd I get the error:

> 00000000 [0x7ff8515d8100] pcscdaemon.c:632:main() cannot create /run/pcscd: No such file or directory

Basing myself on the brew [formula](https://github.com/Homebrew/homebrew-core/blob/3e279da1ed53b4c1ca7ea175eda4898431123601/Formula/p/pcsc-lite.rb#L4):  I downloaded 2.0.3 and built from source:

```
./configure \
  --disable-dependency-tracking \
  --disable-silent-rules \
  --prefix=/usr/local/ \
  --sysconfdir=/usr/local/etc/ \
  --disable-libsystemd \
  --disable-polkit

make
```

I then tried running the `./src/pcscd` and get the same error.

Based on the defaults of these two `configure` lines, run should have resolved to /usr/local/var/run:

```
  --localstatedir=DIR     modifiable single-machine data [PREFIX/var]
  --runstatedir=DIR       modifiable per-process data [LOCALSTATEDIR/run]
```

**Comment by LudovicRousseau** [comment]
pcsc-lite is not supported on macOS.
