### ISSUE TITLE
[Build] Meson ignoring prefix for binary location

### ISSUE THREAD

**Issue by freswa** [LudovicRousseau/PCSC#179]
I tried to switch the Arch Linux build to meson, but run into an error.

`pcscd` ends up in the wrong directory (`/bin/pcscd`instead of `/usr/bin/pcscd`). At the moment the `prefix` is ignored in [this](https://github.com/LudovicRousseau/PCSC/blob/da69dda356dc79300a997631f94efed7190d30a6/meson.build#L146) line. Either we remove the leading slash to use the default behavior or we use something like 

```
prefix = get_option('prefix')
join_paths(prefix, get_option('sbindir'))`
```

**Comment by LudovicRousseau** [comment]
Try something like:
```
meson setup builddir --prefix /usr --sbindir usr/bin
```
It is important to use `usr/bin` without the initial /

You can check what meson understood using `meson configure`. 

Do you know other projects that use `join_paths(prefix, get_option('sbindir'))` as you suggest?

**Comment by freswa** [comment]
Technically, `--prefix /usr --sbindir usr/bin` works but that collides with our [defaults](https://gitlab.archlinux.org/archlinux/packaging/packages/meson/-/blob/main/arch-meson?ref_type=heads) and it looks like a duplicate to me. If I set the prefix, which would be used to install pcsc into arbitrary locations like `/usr/local` or `/opt/pcsc-1.2.2`, `--sbindir usr/bin` or `--sbindir usr/sbin` don't have the intended effect anymore. And having a look at the [upstream defaults](https://mesonbuild.com/Builtin-options.html) it seems to me that `sbin` or `bin` is the choice with far more compatibility across distros.

Maybe I can help you out with this one, what is the reason to expect `--sbindir usr/bin`?

> Do you know other projects that use join_paths(prefix, get_option('sbindir')) as you suggest?

See e.g. the [fwupd project](https://github.com/fwupd/fwupd/blob/acb67931acf1fea8b311b1eb9e9c67887c48f69c/meson.build#L181).

**Comment by LudovicRousseau** [comment]
Fixed in https://github.com/LudovicRousseau/PCSC/commit/960e367edc01518b90684ffff99010ee07ae1bd4
Thanks
