### ISSUE TITLE
Meson is missing the creation of doxygen.conf

### ISSUE THREAD

**Issue by Jakuje** [LudovicRousseau/PCSC#182]
When building the latest version 2.2.0 with meson, I do not get `doxygen.conf` generated from `doxygen.conf.in` causing Fedora build to fail as we use that one to gerenate doc supbackage.

It should be just matter of passing it to `configure_file` (maybe under the conditional for generating separate docs?). Something like this works already:
```
diff --git a/meson.build b/meson.build
index ab23b161..373e32a3 100644
--- a/meson.build
+++ b/meson.build
@@ -251,6 +251,9 @@ configure_file(output : 'pcscd.8',
   input : 'doc/pcscd.8.in',
   install_dir : join_paths(get_option('mandir'), 'man8'),
   configuration : confgen_data)
+configure_file(output : 'doxygen.conf',
+  input : 'doc/doxygen.conf.in',
+  configuration : confgen_data)
 if get_option('serial')
 configure_file(output : 'reader.conf.5',
   input : 'doc/reader.conf.5.in',
```
Its question if it makes sense to keep it like this or we want to allow building the docs in some more standard way than calling `doxygen` from spec file directly.

**Comment by LudovicRousseau** [comment]
Exact.

Generating the `doxygen.conf` file will not be enough.
I generate the documentation using `make doxygen` and this will not work with meson.

What "more standard way" are you thinking about?

**Comment by Jakuje** [comment]
This would be enough for the way how we do it in Fedora package now as we run doxygen directly during build:

https://src.fedoraproject.org/rpms/pcsc-lite/blob/rawhide/f/pcsc-lite.spec#_104

By standard way I meant checking the doxygen presence in meson and creating the API docs as part of meson build, by default or with specific target.

**Comment by LudovicRousseau** [comment]
Done in https://github.com/LudovicRousseau/PCSC/commit/a217c5c52d6568c997c351ad3d8633e8aa4a2ec2

Do you think meson should also install the documentation?
If yes where?

**Comment by LudovicRousseau** [comment]
I did not know the pcsc-lite-doc fedora package.

On my side. I generate the documentation to populate the web site https://pcsclite.apdu.fr/api/
