### ISSUE TITLE
Make pcsc-spy python3-ready

### ISSUE THREAD

**Issue by xmj** [LudovicRousseau/PCSC#19]
Using FreeBSD `12.0-CURRENT` with Python3 as default python, I noticed that the amount of changes to pcsc-spy for adding python3 compatibility are quite trivial.

1. Use parentheses around all print statements
2. Queue becomes queue, so this would work:
```
try:
    from Queue import Queue
except ImportError:
    from queue import Queue
```

That's it really.

**Comment by LudovicRousseau** [comment]
Fixed in https://github.com/LudovicRousseau/PCSC/commit/59489545659447d297e51f3c3c281f377d350851

Thanks
