### ISSUE TITLE
meson setup builddir error

### ISSUE THREAD

**Issue by vinimaniaci2** [LudovicRousseau/PCSC#191]
Hello, I have the following error when executing the command in the title:
~/PCSC-master$ meson setup builddir

The Meson build system
Version: 0.53.2
Source dir: /home/viniciusnascimento/PCSC-master
Build dir: /home/viniciusnascimento/PCSC-master/builddir
Build type: native build
Project name: pcsc-lite
Project version: 2.2.3
C compiler for the host machine: cc (gcc 9.4.0 "cc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0")
C linker for the host machine: cc ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64
Checking for function "getrandom" : YES 
Checking for function "secure_getenv" : YES 
Checking for function "getopt_long" : YES 
Program flex found: YES (/usr/bin/flex)
Run-time dependency threads found: YES
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency libudev found: YES 245
Library dl found: YES
Run-time dependency polkit-gobject-1 found: YES 0.105
Run-time dependency libsystemd found: YES 245

meson.build:234:0: ERROR: Function does not take positional arguments.

Thanks!

**Comment by LudovicRousseau** [comment]
Upgrade meson to a newer version.
It is a known issue on Ubuntu 20.04.

**Comment by LudovicRousseau** [comment]
You can also still generate and use `./configure` as documented in https://blog.apdu.fr/posts/2024/05/pcsc-lite-now-uses-meson-build-tool/

**Comment by LudovicRousseau** [comment]
"fixed" in https://github.com/LudovicRousseau/PCSC/commit/b81bc9b6d7f2766fa9d0be4b711abde4b1ef20a5

Thanks for the bug report
