### ISSUE TITLE
Problem with usbdropdir'

### ISSUE THREAD

**Issue by ManiekGrob86** [LudovicRousseau/PCSC#192]
During making command /pcsc-lite-2.2.2$ sudo meson setup builddir
The Meson build system
Version: 1.0.1
Source dir: /home/XXX/pcsc-lite-2.2.2
Build dir: /home/XXX/pcsc-lite-2.2.2/builddir
Build type: native build
Project name: pcsc-lite
Project version: 2.2.2
C compiler for the host machine: cc (gcc 12.2.0 "cc (Debian 12.2.0-14) 12.2.0")
C linker for the host machine: cc ld.bfd 2.40
Host machine cpu family: x86_64
Host machine cpu: x86_64

meson.build:16:0: ERROR: Tried to access unknown option 'usbdropdir'.

A full log can be found at /home/groblicamariusz/pcsc-lite-2.2.2/builddir/meson-logs/meson-log.txt

And i dont go farther :(

**Comment by LudovicRousseau** [comment]
1. do not use sudo
2. please attach the full log file `/home/groblicamariusz/pcsc-lite-2.2.2/builddir/meson-logs/meson-log.txt`

**Comment by ManiekGrob86** [comment]
[meson-log.txt](https://github.com/user-attachments/files/15956366/meson-log.txt)

Without SUDO gives

meson.build:17:0: ERROR: Tried to access unknown option 'usbdropdir'.

A full log can be found at /home/groblicamariusz/PCSC-master/builddir/meson-logs/meson-log.txt
groblicamariusz@penguin:~/PCSC-master$ meson setup builddir
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 194, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/msetup.py", line 310, in run
    app.generate()
  File "/usr/lib/python3/dist-packages/mesonbuild/msetup.py", line 183, in generate
    mlog.initialize(env.get_log_dir(), self.options.fatal_warnings)
  File "/usr/lib/python3/dist-packages/mesonbuild/mlog.py", line 111, in initialize
    log_file = open(os.path.join(logdir, log_fname), 'w', encoding='utf-8')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/home/groblicamariusz/PCSC-master/builddir/meson-logs/meson-log.txt'

ERROR: Unhandled python OSError. This is probably not a Meson bug, but an issue with your build environment.
[meson-log.txt](https://github.com/user-attachments/files/15956374/meson-log.txt)

**Comment by LudovicRousseau** [comment]
Remove the directory `/home/groblicamariusz/PCSC-master/builddir` and try again.

What is the output of the command: `ls -l /home/groblicamariusz/PCSC-master`?

**Comment by ManiekGrob86** [comment]
ok i reinstall it. but now I have so problem

/usr/sbin/pcscd --version show me
pcsc-lite version 1.9.9.
Copyright (C) 1999-2002 by David Corcoran [corcoran@musclecard.com](mailto:corcoran@musclecard.com).
Copyright (C) 2001-2022 by Ludovic Rousseau [ludovic.rousseau@free.fr](mailto:ludovic.rousseau@free.fr).
Copyright (C) 2003-2004 by Damien Sauveron [sauveron@labri.fr](mailto:sauveron@labri.fr).
Report bugs to [pcsclite-muscle@lists.infradead.org](mailto:pcsclite-muscle@lists.infradead.org).
Enabled features: Linux x86_64-pc-linux-gnu libsystemd serial usb libudev usbdropdir=/usr/lib/pcsc/drivers ipcdir=/run/pcscd filter configdir=/etc/reader.conf.d
MAX_READERNAME: 128, PCSCLITE_MAX_READERS_CONTEXTS: 16

command pcsc-relay --emulator vpcd shows
Could not connect to PC/SC Service
Service not available.

pcsc_scan
PC/SC device scanner
V 1.6.2 (c) 2001-2022, Ludovic Rousseau [ludovic.rousseau@free.fr](mailto:ludovic.rousseau@free.fr)
SCardEstablishContext: Service not available.

and after run sudo pcscd -fda

i become errors

[...]
00000002 [140597508720640] configfile.l:272:tok_error() tok_error: invalid value line 33022 in /etc/reader.conf.d/get-pip.py: &
00000002 [140597508720640] configfile.l:272:tok_error() tok_error: invalid value line 33022 in /etc/reader.conf.d/get-pip.py: bb
00000001 [140597508720640] configfile.l:272:tok_error() tok_error: invalid value line 33023 in /etc/reader.conf.d/get-pip.py: ""
00000002 [140597508720640] configfile.l:272:tok_error() tok_error: invalid value line 33025 in /etc/reader.conf.d/get-pip.py: if
00000002 [140597508720640] configfile.l:272:tok_error() tok_error: invalid value line 33025 in /etc/reader.conf.d/get-pip.py: ==
00000002 [140597508720640] configfile.l:272:tok_error() tok_error: invalid value line 33025 in /etc/reader.conf.d/get-pip.py: :
00000001 [140597508720640] configfile.l:272:tok_error() tok_error: invalid value line 33026 in /etc/reader.conf.d/get-pip.py: (
00000002 [140597508720640] configfile.l:272:tok_error() tok_error: invalid value line 33026 in /etc/reader.conf.d/get-pip.py: )
00000037 [140597508720640] readerfactory.c:1093:RFInitializeReader() Attempting startup of Virtual PCD 00 00 using /usr/lib/pcsc/drivers/serial/libifdvpcd.so
00000151 [140597508720640] readerfactory.c:968:RFBindFunctions() Loading IFD Handler 3.0
00000035 [140597508720640] ifd-vpcd.c:126:IFDHCreateChannel() Waiting for virtual ICC on port 35963
00000091 [140597508720640] ifd-vpcd.c:340:IFDHGetCapabilities() unknown tag 4019
00000003 [140597508720640] readerfactory.c:393:RFAddReader() Using the pcscd polling thread
00000070 [140597508720640] readerfactory.c:524:RFAddReader() Driver is slot thread safe
00000003 [140597508720640] readerfactory.c:1093:RFInitializeReader() Attempting startup of Virtual PCD 00 01 using /usr/lib/pcsc/drivers/serial/libifdvpcd.so
00000002 [140597508720640] readerfactory.c:881:RFLoadReader() Reusing already loaded driver for /usr/lib/pcsc/drivers/serial/libifdvpcd.so
00000003 [140597508720640] readerfactory.c:968:RFBindFunctions() Loading IFD Handler 3.0
00000007 [140597508720640] ifd-vpcd.c:126:IFDHCreateChannel() Waiting for virtual ICC on port 35964
00000018 [140597508720640] ifd-vpcd.c:340:IFDHGetCapabilities() unknown tag 4019
00000002 [140597508720640] readerfactory.c:558:RFAddReader() Using the pcscd polling thread
00000038 [140597508720640] pcscdaemon.c:799:at_exit() cleaning /run/pcscd
00000017 [140597508720640] pcscdaemon.c:829:clean_temp_files() Cannot remove /run/pcscd/pcscd.comm: No such file or directory
00000007 [140597508720640] pcscdaemon.c:835:clean_temp_files() Cannot remove /run/pcscd/pcscd.pid: No such file or directory

**Comment by ManiekGrob86** [comment]
ls -l /home/groblicamariusz/PCSC-master
total 220
-rw-r--r-- 1 groblicamariusz groblicamariusz   250 Jun 23 18:00 AUTHORS
-rwxr-xr-x 1 groblicamariusz groblicamariusz   385 Jun 23 18:00 bootstrap
drwxr-xr-x 1 groblicamariusz groblicamariusz   900 Jun 27 08:32 builddir
-rw-r--r-- 1 groblicamariusz groblicamariusz 83428 Jun 23 18:00 ChangeLog
-rwxr-xr-x 1 groblicamariusz groblicamariusz   334 Jun 23 18:00 clang-analyze.sh
-rw-r--r-- 1 groblicamariusz groblicamariusz 13681 Jun 23 18:00 configure.ac
-rw-r--r-- 1 groblicamariusz groblicamariusz  4620 Jun 23 18:00 COPYING
-rwxr-xr-x 1 groblicamariusz groblicamariusz   258 Jun 23 18:00 c.sh
drwxr-xr-x 1 groblicamariusz groblicamariusz   238 Jun 23 18:00 doc
drwxr-xr-x 1 groblicamariusz groblicamariusz    84 Jun 23 18:00 etc
-rw-r--r-- 1 groblicamariusz groblicamariusz 35147 Jun 23 18:00 GPL-3.0.txt
-rw-r--r-- 1 groblicamariusz groblicamariusz   463 Jun 23 18:00 HELP
-rw-r--r-- 1 groblicamariusz groblicamariusz   347 Jun 23 18:00 Makefile.am
-rw-r--r-- 1 groblicamariusz groblicamariusz  7998 Jun 23 18:00 meson.build
-rw-r--r-- 1 groblicamariusz groblicamariusz  1395 Jun 23 18:00 meson.options
lrwxrwxrwx 1 groblicamariusz groblicamariusz    13 Jun 24 19:23 meson_options.txt -> meson.options
-rw-r--r-- 1 groblicamariusz groblicamariusz    34 Jun 23 18:00 NEWS
-rw-r--r-- 1 groblicamariusz groblicamariusz  6426 Jun 27 08:14 pcsc-spy.1
-rw-r--r-- 1 groblicamariusz groblicamariusz  4335 Jun 23 18:00 README
-rw-r--r-- 1 groblicamariusz groblicamariusz   353 Jun 23 18:00 README.md
-rw-r--r-- 1 groblicamariusz groblicamariusz   585 Jun 23 18:00 SECURITY
-rwxr-xr-x 1 groblicamariusz groblicamariusz   512 Jun 23 18:00 splint.sh
drwxr-xr-x 1 groblicamariusz groblicamariusz  1288 Jun 23 18:00 src
-rw-r--r-- 1 groblicamariusz groblicamariusz    10 Jun 23 18:00 stamp-h.in
drwxr-xr-x 1 groblicamariusz groblicamariusz  1936 Jun 23 18:00 UnitaryTests

**Comment by LudovicRousseau** [comment]
Why do you have the file `/etc/reader.conf.d/get-pip.py`?

Is your build problem solved now?

**Comment by LudovicRousseau** [comment]
No news since more than a month.
Closing
