### ISSUE TITLE
Build issue with Meson not linking libpcsclite against libpthread

### ISSUE THREAD

**Issue by brad0** [LudovicRousseau/PCSC#200]
pcsc 2.2.3

When switching our port from autoconf to Meson we noticed that the built shared library for libpcsclite does not link against libpthread which breaks programs dependent on libpcsclite.

**Comment by LudovicRousseau** [comment]
`libpcsc_real` is linked against pthread. See https://github.com/LudovicRousseau/PCSC/blob/master/meson.build#L170
But `libpcsclite` is not because it does not use threads.

What if the error message exactly?
Does your application uses pthreads?

**Comment by brad0** [comment]
> `libpcsc_real` is linked against pthread. See https://github.com/LudovicRousseau/PCSC/blob/master/meson.build#L170 But `libpcsclite` is not because it does not use threads.

But it's not.

Dynamic Section:
  SONAME      libpcsclite_real.so.0.0
  RELA        0xef8
  RELASZ      0x78
  RELAENT     0x18
  RELACOUNT   0x2
  JMPREL      0xf70
  PLTRELSZ    0x408
  PLTGOT      0xce40
  PLTREL      0x7
  SYMTAB      0x350
  SYMENT      0x18
  STRTAB      0xc0c
  STRSZ       0x2eb
  GNU_HASH    0x968
  HASH        0x9fc
  FINI_ARRAY  0xcce0
  FINI_ARRAYSZ 0x8
  INIT        0xb350
  FINI        0xb370

With the autoconf built pcsc the libraries ARE linked against libpthread.

**Comment by LudovicRousseau** [comment]
Fixed in https://github.com/LudovicRousseau/pcsc-tools/commit/6acb170784b0349b3e43682d0ba1e3131652dc8e

Thanks
