### ISSUE TITLE
pcscd build feature "filter" not reported

### ISSUE THREAD

**Issue by leuthold-at-ehex-de** [LudovicRousseau/PCSC#202]
### Versions

* pcsc-lite 2.2.x
* the output of the command `/usr/sbin/pcscd --version`
```
pcsc-lite version 2.2.3
Copyright (C) 1999-2002 by David Corcoran <corcoran@musclecard.com>.
Copyright (C) 2001-2024 by Ludovic Rousseau <ludovic.rousseau@free.fr>.
Copyright (C) 2003-2004 by Damien Sauveron <sauveron@labri.fr>.
Report bugs to <pcsclite-muscle@lists.infradead.org>.
Enabled features: USB serial libudev Linux x86_64 ipcdir=/run/pcscd usbdropdir=/usr/lib/pcsc/drivers serialconfdir=/etc/reader.conf.d
MAX_READERNAME: 128, PCSCLITE_MAX_READERS_CONTEXTS: 16
```

### Issue

`pcscd --version` does not report all build flags, at least "filter" is missing even though it is enabled by default. Looks like [mason.build](https://github.com/LudovicRousseau/PCSC/blob/master/meson.build#L48) is incomplete.

**Comment by LudovicRousseau** [comment]
Fixed in https://github.com/LudovicRousseau/PCSC/commit/daf1d93c72136f32378db734968ee5703f40c736

Thanks
