### ISSUE TITLE
SCL011G Contactless Reader not initialized correctly. Unusable.

### ISSUE THREAD

**Issue by klawdhfzasjhaa** [LudovicRousseau/PCSC#204]
I'm a noob, please help me. :)

### Versions

* smart card reader driver name and version: scl generic 2.09 (https://files.identiv.com/products/smart-card-readers/contactless/scl010-011/Linux_Driver_Ver2.09.zip)
* pcsc-lite version: 2.2.3
* the output of the command `/usr/sbin/pcscd --version`:
pcsc-lite version 2.2.3
Copyright (C) 1999-2002 by David Corcoran <corcoran@musclecard.com>.
Copyright (C) 2001-2024 by Ludovic Rousseau <ludovic.rousseau@free.fr>.
Copyright (C) 2003-2004 by Damien Sauveron <sauveron@labri.fr>.
Report bugs to <pcsclite-muscle@lists.infradead.org>.
Enabled features: USB serial libudev polkit systemd Linux x86_64 ipcdir=/run/pcscd usbdropdir=/usr/lib/pcsc/drivers serialconfdir=/etc/reader.conf.d
MAX_READERNAME: 128, PCSCLITE_MAX_READERS_CONTEXTS: 16

### Platform

* 6.6.41-1-MANJARO (64-bit)
* Smart card middleware name and version: pcsclite 2.2.3
* Smart card reader manufacturer name and reader model name: Identiv, Inc -> SCL011G Contactless Reader
* Smart card name: SCL011G Contactless Reader

### Issue

* What do you do?: Plug in the smart card reader into USB port
* What result do you expect?: Reader is usable in AusweisApp2
* What result do you get instead?: Reader is is not initialized correctly

### Log

Then you shall generate a complete log (do not truncate it):

00000000 ../PCSC/src/debuglog.c:392:DebugLogSetLevel() debug level=debug
00000017 ../PCSC/src/debuglog.c:413:DebugLogSetCategory() Debug options: APDU
00000005 [139714683329728] ../PCSC/src/pcscdaemon.c:359:main() Force colored logs
00000028 [139714683329728] ../PCSC/src/utils.c:82:GetDaemonPid() Can't open /run/pcscd/pcscd.pid: No such file or directory
00000082 [139714683329728] ../PCSC/src/configfile.l:365:DBGetReaderList() Parsing conf file: /etc/reader.conf.d
00000008 [139714683329728] ../PCSC/src/pcscdaemon.c:669:main() pcsc-lite 2.2.3 daemon ready.
00000055 [139714683329728] ../PCSC/src/pcscdaemon.c:752:main() Using drivers directory: /usr/lib/pcsc/drivers
00002732 [139714683329728] ../PCSC/src/hotplug_libudev.c:299:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0002, path: /dev/bus/usb/001/001
00000100 [139714683329728] ../PCSC/src/hotplug_libudev.c:299:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0002, path: /dev/bus/usb/001/001
00000099 [139714683329728] ../PCSC/src/hotplug_libudev.c:299:get_driver() Looking for a driver for VID: 0x13D3, PID: 0x56BA, path: /dev/bus/usb/001/002
00000101 [139714683329728] ../PCSC/src/hotplug_libudev.c:299:get_driver() Looking for a driver for VID: 0x13D3, PID: 0x56BA, path: /dev/bus/usb/001/002
00000097 [139714683329728] ../PCSC/src/hotplug_libudev.c:299:get_driver() Looking for a driver for VID: 0x13D3, PID: 0x56BA, path: /dev/bus/usb/001/002
00000092 [139714683329728] ../PCSC/src/hotplug_libudev.c:299:get_driver() Looking for a driver for VID: 0x13D3, PID: 0x56BA, path: /dev/bus/usb/001/002
00000090 [139714683329728] ../PCSC/src/hotplug_libudev.c:299:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0002, path: /dev/bus/usb/001/001
00000098 [139714683329728] ../PCSC/src/hotplug_libudev.c:299:get_driver() Looking for a driver for VID: 0x06CB, PID: 0x00BD, path: /dev/bus/usb/001/003
00000167 [139714683329728] ../PCSC/src/hotplug_libudev.c:299:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0003, path: /dev/bus/usb/002/001
00000274 [139714683329728] ../PCSC/src/hotplug_libudev.c:299:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0002, path: /dev/bus/usb/003/001
00000268 [139714683329728] ../PCSC/src/hotplug_libudev.c:299:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0003, path: /dev/bus/usb/004/001
30046176 [139714674931392] ../PCSC/src/hotplug_libudev.c:646:HPEstablishUSBNotifications() USB Device add
00000169 [139714674931392] ../PCSC/src/hotplug_libudev.c:299:get_driver() Looking for a driver for VID: 0x04E6, PID: 0x5293, path: /dev/bus/usb/001/006
00000005 [139714674931392] ../PCSC/src/hotplug_libudev.c:420:HPAddDevice() Adding USB device: SCL011G Contactless Reader
00000072 [139714674931392] ../PCSC/src/readerfactory.c:1091:RFInitializeReader() Attempting startup of SCL011G Contactless Reader [SCL01x Contactless Reader] (00000741000005) 00 00 using /usr/lib/pcsc/drivers/SCLGENERIC.bundle/Contents/Linux/libSCLGENERIC.so.2.09
00000026 [139714674931392] ../PCSC/src/dyn_unix.c:59:DYN_LoadLibrary() /usr/lib/pcsc/drivers/SCLGENERIC.bundle/Contents/Linux/libSCLGENERIC.so.2.09: /usr/lib/pcsc/drivers/SCLGENERIC.bundle/Contents/Linux/libSCLGENERIC.so.2.09: wrong ELF class: ELFCLASS32
00000003 [139714674931392] ../PCSC/src/readerfactory.c:1099:RFInitializeReader() RFLoadReader failed: 0x80100014
00000002 [139714674931392] ../PCSC/src/readerfactory.c:371:RFAddReader() SCL011G Contactless Reader [SCL01x Contactless Reader] (00000741000005) init failed.
00000002 [139714674931392] ../PCSC/src/hotplug_libudev.c:517:HPAddDevice() Failed adding USB device: SCL011G Contactless Reader
^C10415273 [139714683324096] ../PCSC/src/pcscdaemon.c:190:signal_thread() Received signal: 2
00000018 [139714683324096] ../PCSC/src/pcscdaemon.c:224:signal_thread() Preparing for suicide
00001443 [139714683329728] ../PCSC/src/hotplug_libudev.c:710:HPStopHotPluggables() Hotplug stopped
01000584 [139714683329728] ../PCSC/src/winscard_svc.c:157:ContextsDeinitialize() remaining threads: 0
00000028 [139714683329728] ../PCSC/src/readerfactory.c:1376:RFCleanupReaders() entering cleaning function
00000011 [139714683329728] ../PCSC/src/pcscdaemon.c:807:at_exit() cleaning /run/pcscd

**Comment by LudovicRousseau** [comment]
```
 00000026 [139714674931392] ../PCSC/src/dyn_unix.c:59:DYN_LoadLibrary() /usr/lib/pcsc/drivers/SCLGENERIC.bundle/Contents/Linux/libSCLGENERIC.so.2.09: /usr/lib/pcsc/drivers/SCLGENERIC.bundle/Contents/Linux/libSCLGENERIC.so.2.09: wrong ELF class: ELFCLASS32
```

It looks like you are trying to use a 32-bits driver on a 64-bits system.
This can't work.

You should be able to use [my CCID driver](https://ccid.apdu.fr/) for your reader https://ccid.apdu.fr/ccid/shouldwork.html#0x04E60x5293

**Comment by klawdhfzasjhaa** [comment]
Perfect, with your driver, it works immediately. :D

pcscd.service is still unhappy, but it works: _Referenced but unset environment variable evaluates to an empty string: PCSCD_ARGS_

**Comment by LudovicRousseau** [comment]
You can ignore this log
See https://blog.apdu.fr/posts/2021/08/pcsc-lite-configuration-using/
