### ISSUE TITLE
Declared version in autoconf is out of sync

### ISSUE THREAD

**Issue by Maryse47** [LudovicRousseau/PCSC#205]
Declared version in autoconf is still at [2.2.0](https://github.com/LudovicRousseau/PCSC/blob/master/configure.ac#L6) which may be confusing for anyone using it to build latest pcsc. Unfortunately it's not fixable for past releases so bumping it is something to remember for future releases. Or maybe autoconf is no longer supported?

**Comment by LudovicRousseau** [comment]
Yes, autoconf is no more maintained.

I keep the files just in case meson does not work for you. In that case I would appreciate a bug report.

**Comment by Maryse47** [comment]
Ok
