### ISSUE TITLE
pcscd+rpi+acr122 = error

### ISSUE THREAD

**Issue by ramiil-kun** [LudovicRousseau/PCSC#21]
My Raspberry Pi B can't find reader(ACR122U-A9)

What info I should provide?

root@raspberrypi:/opt# pcscd -daf
00000000 pcscdaemon.c:263:main() pcscd set to foreground with debug send to stdout
00006052 configfile.l:283:DBGetReaderListDir() Parsing conf directory: /etc/reader.conf.d
00004974 configfile.l:317:DBGetReaderListDir() Skipping non regular file: .
00003208 configfile.l:317:DBGetReaderListDir() Skipping non regular file: ..
00000160 configfile.l:355:DBGetReaderList() Parsing conf file: /etc/reader.conf.d/libccidtwin
00000674 pcscdaemon.c:569:main() pcsc-lite 1.8.13 daemon ready.
00024974 hotplug_libudev.c:296:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0002, path: /dev/bus/usb/001/001
00007173 hotplug_libudev.c:296:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0002, path: /dev/bus/usb/001/001
00005275 hotplug_libudev.c:296:get_driver() Looking for a driver for VID: 0x0424, PID: 0x9512, path: /dev/bus/usb/001/002
00005180 hotplug_libudev.c:296:get_driver() Looking for a driver for VID: 0x0424, PID: 0xEC00, path: /dev/bus/usb/001/003
00005289 hotplug_libudev.c:296:get_driver() Looking for a driver for VID: 0x0424, PID: 0x9512, path: /dev/bus/usb/001/002

**Comment by LudovicRousseau** [comment]
First step is http://pcsclite.alioth.debian.org/ccid.html#support

**Comment by ramiil-kun** [comment]
Card reader: is ACR122U-A9 from noname chineese manufacturer

Dont know how to get:
* CCID driver version
* pcsc-lite version
* Smart card middleware name and version
* Smart card name

pi@raspberrypi:~ $ sudo pcscd --version
pcsc-lite version 1.8.13.
Copyright (C) 1999-2002 by David Corcoran <corcoran@musclecard.com>.
Copyright (C) 2001-2011 by Ludovic Rousseau <ludovic.rousseau@free.fr>.
Copyright (C) 2003-2004 by Damien Sauveron <sauveron@labri.fr>.
Report bugs to <muscle@lists.musclecard.com>.
Enabled features: Linux arm-unknown-linux-gnueabihf serial usb libudev usbdropdir=/usr/lib/pcsc/drivers ipcdir=/var/run/pcscd configdir=/etc/reader.conf.d

pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.9.28+ #998 Mon May 15 16:50:35 BST 2017 armv6l GNU/Linux

Logifile is:
00000000 debuglog.c:292:DebugLogSetLevel() debug level=debug
00003082 debuglog.c:321:DebugLogSetCategory() Debug options: APDU
^[[36m00002417^[[0m ^[[34mpcscdaemon.c:268:main() Force colored logs^[[0m
^[[36m00002722^[[0m ^[[01;31mutils.c:84:GetDaemonPid() Can't open /var/run/pcscd/pcscd.pid: No such file or directory^[[0m
^[[36m00002785^[[0m configfile.l:283:DBGetReaderListDir() Parsing conf directory: /etc/reader.conf.d
^[[36m00005186^[[0m configfile.l:317:DBGetReaderListDir() Skipping non regular file: .
^[[36m00001673^[[0m configfile.l:317:DBGetReaderListDir() Skipping non regular file: ..
^[[36m00001543^[[0m configfile.l:355:DBGetReaderList() Parsing conf file: /etc/reader.conf.d/libccidtwin
^[[36m00002684^[[0m ^[[34mpcscdaemon.c:569:main() pcsc-lite 1.8.13 daemon ready.^[[0m
^[[36m00032945^[[0m hotplug_libudev.c:296:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0002, path: /dev/bus/usb/001/001
^[[36m00003906^[[0m hotplug_libudev.c:296:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0002, path: /dev/bus/usb/001/001
^[[36m00004141^[[0m hotplug_libudev.c:296:get_driver() Looking for a driver for VID: 0x0424, PID: 0x9512, path: /dev/bus/usb/001/009
^[[36m00003928^[[0m hotplug_libudev.c:296:get_driver() Looking for a driver for VID: 0x0424, PID: 0xEC00, path: /dev/bus/usb/001/010
^[[36m00003987^[[0m hotplug_libudev.c:296:get_driver() Looking for a driver for VID: 0x0424, PID: 0x9512, path: /dev/bus/usb/001/009

**Comment by LudovicRousseau** [comment]
Next step is http://pcsclite.alioth.debian.org/ccid.html#CCID_compliant

**Comment by ramiil-kun** [comment]
This reader works on my x86 pc with debian jessie. 
lsusb don't show my device on both pc and raspberry.
BTW, I do everything as on your instruction. But output.txt is empty, and I get this in stderr

Parsing USB bus/device: 0424:EC00 (bus 1, device 3)
 idVendor:  0x0424  Can't get iManufacturer string
 idProduct: 0xEC00  Can't get iProduct string
  NOT a CCID/ICCD device
Parsing USB bus/device: 0424:9512 (bus 1, device 2)
 idVendor:  0x0424  Can't get iManufacturer string
 idProduct: 0x9512  Can't get iProduct string
  NOT a CCID/ICCD device
Parsing USB bus/device: 1D6B:0002 (bus 1, device 1)
 idVendor:  0x1D6B  iManufacturer: Linux 4.9.28+ dwc_otg_hcd
 idProduct: 0x0002  iProduct: DWC OTG Controller
  NOT a CCID/ICCD device

**Comment by ramiil-kun** [comment]
That I get after "make install" for ccid drivers and reboot my raspberry.

pcscd -f -d
00000000 debuglog.c:292:DebugLogSetLevel() debug level=debug
00005393 utils.c:84:GetDaemonPid() Can't open /var/run/pcscd/pcscd.pid: No such file or directory
00004629 configfile.l:283:DBGetReaderListDir() Parsing conf directory: /etc/reader.conf.d
00006149 configfile.l:317:DBGetReaderListDir() Skipping non regular file: .
00000209 configfile.l:317:DBGetReaderListDir() Skipping non regular file: ..
00000142 configfile.l:355:DBGetReaderList() Parsing conf file: /etc/reader.conf.d/libccidtwin
00002043 pcscdaemon.c:569:main() pcsc-lite 1.8.13 daemon ready.
00039771 hotplug_libudev.c:296:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0002, path: /dev/bus/usb/001/001
00007043 hotplug_libudev.c:296:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0002, path: /dev/bus/usb/001/001
00004968 hotplug_libudev.c:296:get_driver() Looking for a driver for VID: 0x0424, PID: 0x9512, path: /dev/bus/usb/001/002
00004970 hotplug_libudev.c:296:get_driver() Looking for a driver for VID: 0x0424, PID: 0xEC00, path: /dev/bus/usb/001/003
00005352 hotplug_libudev.c:296:get_driver() Looking for a driver for VID: 0x0424, PID: 0x9512, path: /dev/bus/usb/001/002
00004872 hotplug_libudev.c:296:get_driver() Looking for a driver for VID: 0x072F, PID: 0x2200, path: /dev/bus/usb/001/004
00003663 hotplug_libudev.c:435:HPAddDevice() Adding USB device: ACS ACR122U
00000815 readerfactory.c:1012:RFInitializeReader() Attempting startup of ACS ACR122U 00 00 using /usr/lib/pcsc/drivers/ifd-acsccid.bundle/Contents/Lin
ux/libacsccid.so
00012048 readerfactory.c:897:RFBindFunctions() Loading IFD Handler 3.0
00001515 ifdhandler.c:2611:init_driver() Driver version: 1.1.4
00003223 ifdhandler.c:2628:init_driver() LogLevel: 0x0003
00006434 ifdhandler.c:2639:init_driver() DriverOptions: 0x0000
00000215 ifdhandler.c:2647:init_driver() ACSDriverOptions: 0x0003
00000154 ifdhandler.c:2655:init_driver() ACR38CardVoltage: 0
00004293 ifdhandler.c:2663:init_driver() ACR38CardType: 0
00000828 ifdhandler.c:121:CreateChannelByNameOrChannel() Lun: 0, device: usb:072f/2200:libudev:0:/dev/bus/usb/001/004
00000385 ccid_usb.c:313:OpenUSBByName() Using: /usr/lib/pcsc/drivers/ifd-acsccid.bundle/Contents/Info.plist
00003244 ccid_usb.c:331:OpenUSBByName() ifdManufacturerString: Advanced Card Systems Ltd.
00007215 ccid_usb.c:332:OpenUSBByName() ifdProductString: ACS CCID driver
00000315 ccid_usb.c:333:OpenUSBByName() Copyright: This driver is protected by terms of the GNU Lesser General Public License version 2.1, or (at your
 option) any later version.
00111482 ccid_usb.c:715:OpenUSBByName() Found Vendor/Product: 072F/2200 (ACS ACR122U)
00005228 ccid_usb.c:717:OpenUSBByName() Using USB bus/device: 1/4
00002815 ccid_usb.c:891:OpenUSBByName() bNumDataRatesSupported is 0
01006625 ccid_usb.c:1781:InterruptRead() 1/4: Slot 0: 0x00
00000986 ccid_usb.c:1252:ReadUSB() read failed (1/4): -9 LIBUSB_ERROR_PIPE
00000618 ccid_usb.c:1132:WriteUSB() write failed (1/4): -9 LIBUSB_ERROR_PIPE
00000642 ccid_usb.c:1132:WriteUSB() write failed (1/4): -9 LIBUSB_ERROR_PIPE
00000187 ifdhandler.c:237:CreateChannelByNameOrChannel() failed
00000354 ccid_usb.c:215:close_libusb_if_needed() libusb_exit
00001260 readerfactory.c:1043:RFInitializeReader() Open Port 0x200000 Failed (usb:072f/2200:libudev:0:/dev/bus/usb/001/004)
00000312 readerfactory.c:335:RFAddReader() ACS ACR122U init failed.
00002899 readerfactory.c:558:RFRemoveReader() UnrefReader() count was: 1
00000202 readerfactory.c:1063:RFUnInitializeReader() Attempting shutdown of ACS ACR122U 00 00.
00000138 readerfactory.c:934:RFUnloadReader() Unloading reader driver.
00000558 hotplug_libudev.c:501:HPAddDevice() Failed adding USB device: ACS ACR122U
00000273 readerfactory.c:1012:RFInitializeReader() Attempting startup of ACS ACR122U 00 00 using /usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Linux/
libccid.so
00007693 readerfactory.c:897:RFBindFunctions() Loading IFD Handler 3.0
00005028 ifdhandler.c:1965:init_driver() Driver version: 1.4.27
00008528 ifdhandler.c:1982:init_driver() LogLevel: 0x0003
00011072 ifdhandler.c:1993:init_driver() DriverOptions: 0x0000
00001737 ifdhandler.c:111:CreateChannelByNameOrChannel() Lun: 0, device: usb:072f/2200:libudev:0:/dev/bus/usb/001/004
00000359 ccid_usb.c:302:OpenUSBByName() Using: /usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Info.plist
00008283 ccid_usb.c:320:OpenUSBByName() ifdManufacturerString: Ludovic Rousseau (ludovic.rousseau@free.fr)
00011931 ccid_usb.c:321:OpenUSBByName() ifdProductString: Generic CCID driver
00000206 ccid_usb.c:322:OpenUSBByName() Copyright: This driver is protected by terms of the GNU Lesser General Public License version 2.1, or (at your
 option) any later version.
00023537 ccid_usb.c:656:OpenUSBByName() Found Vendor/Product: 072F/2200 (ACS ACR122U PICC Interface)
00005364 ccid_usb.c:658:OpenUSBByName() Using USB bus/device: 1/4
00000209 ccid_usb.c:717:OpenUSBByName() bNumDataRatesSupported is 0
00008828 ccid_usb.c:849:WriteUSB() write failed (1/4): -9 LIBUSB_ERROR_PIPE
00003792 ccid_usb.c:849:WriteUSB() write failed (1/4): -9 LIBUSB_ERROR_PIPE
00000597 ccid_usb.c:849:WriteUSB() write failed (1/4): -9 LIBUSB_ERROR_PIPE
00000181 ifdhandler.c:195:CreateChannelByNameOrChannel() failed
00000394 ccid_usb.c:189:close_libusb_if_needed() libusb_exit
00006927 readerfactory.c:1043:RFInitializeReader() Open Port 0x200000 Failed (usb:072f/2200:libudev:0:/dev/bus/usb/001/004)
00000335 readerfactory.c:335:RFAddReader() ACS ACR122U init failed.
00000147 readerfactory.c:558:RFRemoveReader() UnrefReader() count was: 1
00000254 readerfactory.c:1063:RFUnInitializeReader() Attempting shutdown of ACS ACR122U 00 00.
00000144 readerfactory.c:934:RFUnloadReader() Unloading reader driver.
00000507 hotplug_libudev.c:511:HPAddDevice() Failed adding USB device: ACS ACR122U
00001534 hotplug_libudev.c:296:get_driver() Looking for a driver for VID: 0x0424, PID: 0x9512, path: /dev/bus/usb/001/002
00029160 hotplug_libudev.c:608:HPEstablishUSBNotifications() USB Device removed
00001258 hotplug_libudev.c:362:HPRemoveDevice() Removing USB device[0]: ACS ACR122U at /dev/bus/usb/001/004

**Comment by LudovicRousseau** [comment]
Both the ACS driver (``/usr/lib/pcsc/drivers/ifd-acsccid.bundle/Contents/Linux/libacsccid.so``) and my own driver (``/usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Linux/libccid.so``) failed to use the device.

I suggest to report the problem to ACS.
See also https://github.com/acshk/acsccid
