### ISSUE TITLE
Mapping reader to the corresponding USB device

### ISSUE THREAD

**Issue by arrowd** [LudovicRousseau/PCSC#212]
Given a reader name returned by `SCardListReaders` I want to figure out what USB device (if any) it corresponds to. In Unix-like terms it is the `/dev/ugenX.Y` files or `/dev/usb/X.Y.Z` ones.

While skimming through MSDN docs I found the [SCARD_READER_CAPABILITIES](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/smclib/ns-smclib-_scard_reader_capabilities) which seemingly provides the info I need. Of course there is no such structure in PCSC.

Would it be possible to implement this in PCSC? Or maybe there is some other API that I didn't find?

**Comment by LudovicRousseau** [comment]
Why do you want to know the USB bus used by the reader? What problem are you trying to solve?

I don't think SCARD_READER_CAPABILITIES will help you. 
But maybe [SCardGetAttrib()](https://pcsclite.apdu.fr/api/group__API.html#gaacfec51917255b7a25b94c5104961602) with attribute `SCARD_ATTR_CHANNEL_ID` can help.

And `SCARD_ATTR_CHANNEL_ID` is already supported by my CCID driver: https://github.com/LudovicRousseau/CCID/blob/master/SCARDGETATTRIB.md

See [SCARD_ATTR_CHANNEL_ID and USB devices](https://blog.apdu.fr/posts/2020/04/scardattrchannelid-and-usb-devices/)

**Comment by arrowd** [comment]
> See [SCARD_ATTR_CHANNEL_ID and USB devices](https://blog.apdu.fr/posts/2020/04/scardattrchannelid-and-usb-devices/)

Thank you, this is exactly what I need!

> Why do you want to know the USB bus used by the reader? What problem are you trying to solve?

It was more an academic interest, I don't have a specific usecase yet.
