### ISSUE TITLE
Yubikey 5 with gpg2 only initialized properly after restarting pcscd

### ISSUE THREAD

**Issue by fansari** [LudovicRousseau/PCSC#215]
### Versions

* smart card reader driver name and version
* pcsc-lite version
* the output of the command `/usr/sbin/pcscd --version`

pcsc-lite-2.3.0-1.fc41.x86_64

pcsc-lite version 2.3.0
Copyright (C) 1999-2002 by David Corcoran <corcoran@musclecard.com>.
Copyright (C) 2001-2024 by Ludovic Rousseau <ludovic.rousseau@free.fr>.
Copyright (C) 2003-2004 by Damien Sauveron <sauveron@labri.fr>.
Report bugs to <pcsclite-muscle@lists.infradead.org>.
Enabled features: USB serial libudev polkit systemd Linux x86_64 ipcdir=/run/pcscd usbdropdir=/usr/lib64/pcsc/drivers serialconfdir=/etc/reader.conf.d
MAX_READERNAME: 128, PCSCLITE_MAX_READERS_CONTEXTS: 16

### Platform

* Operating system or GNU/Linux distribution name and version
* Smart card middleware name and version
* Smart card reader manufacturer name and reader model name
* Smart card name

Fedora 41 Sliverblue
Yubikey 5

(SELinux in permissive mode)

### Issue

* What do you do?
* What result do you expect?
* What result do you get instead?

```
ggp2 --card-status
```
See 

https://github.com/LudovicRousseau/PCSC/issues/65

I expect that "gpg2 --card-status" works after boot.

I have also decribed the issue here:

https://bugzilla.redhat.com/show_bug.cgi?id=2329628

```
fansari@bat:~/.gnupg$ gpg2 --card-status
gpg: selecting card failed: No such device
gpg: OpenPGP card not available: No such device
```
Here I notice that scdaemon is started without the --disable-ccid option altough it is configured.

```
fansari@bat:~/.gnupg$ ps -ef | grep scdaemon | grep -v grep
fansari     5382    5380  0 20:57 ?        00:00:00 scdaemon --multi-server
```

This ~/.gnupg/scdaemon.conf file with "disable-ccid" inside has no effect on the issue. But I am sure that the file is read because when I put an invalid option there scdaemon refuses to start.

Perhaps an interesting finding is that restarting pcscd.service only fixes the issue until I replug the Yubikey.

Restarting the pcscd.socket solves this permanently until next reboot.

Therefore I use now this ugly workaround I have described in the bugzilla ticket.

### Log

I see this after booting in "systemcdtl status pcscd"

```
Dec 07 20:55:38 bat.localdomain systemd[1]: Started pcscd.service - PC/SC Smart Card Daemon.
Dec 07 20:55:38 bat.localdomain (pcscd)[2487]: pcscd.service: Referenced but unset environment variable evaluates to an empty string: PCSCD_ARGS
Dec 07 20:55:56 bat.localdomain pcscd[2487]: 00000000 ../src/auth.c:145:IsClientAuthorized() Process 2607 (user: 987) is NOT authorized for action: access_pcsc
Dec 07 20:55:56 bat.localdomain pcscd[2487]: 00000214 ../src/winscard_svc.c:357:ContextThread() Rejected unauthorized PC/SC client
Dec 07 20:55:56 bat.localdomain pcscd[2487]: 00398568 ../src/auth.c:145:IsClientAuthorized() Process 2365 (user: 42) is NOT authorized for action: access_pcsc
Dec 07 20:55:56 bat.localdomain pcscd[2487]: 00000345 ../src/winscard_svc.c:357:ContextThread() Rejected unauthorized PC/SC client
```

These auth.c and winscard_svc.c messages vanish after once restarting pcscd.service. I see them only after boot before first restart of pcscd.service.

But even after that if I replug the Yubikey it does not work but these message do not reappear. So maybe they are not related to the real issue.

Only restarting pcscd.socket solves the issue if you want to replug the Yubikey.

**Comment by LudovicRousseau** [comment]
See https://blog.apdu.fr/posts/2024/04/gnupg-and-pcsc-conflicts-episode-2/

It looks like a bug in GnuPG if `disable-ccid` option is not used.

You can also try this:
1. plug the Yubikey
1. start pcscd using the `pcsc_scan` command
1. run `ggp2 --card-status` command

Does it work?

**Comment by fansari** [comment]
When I disable pcscd.socket and boot my PC and the run pssc_scan I get this:

```
fansari@bat:~$ pcsc_scan
PC/SC device scanner
V 1.7.0 (c) 2001-2022, Ludovic Rousseau <ludovic.rousseau@free.fr>
SCardEstablishContext: Service not available.
```

When I enable pcscd.socket and start my PC and then run pscs_scan I get this:

```
fansari@bat:~$ pcsc_scan
PC/SC device scanner
V 1.7.0 (c) 2001-2022, Ludovic Rousseau <ludovic.rousseau@free.fr>
Using reader plug'n play mechanism
Scanning present readers...
0: Yubico YubiKey OTP+FIDO+CCID 00 00

Sun Dec  8 14:02:24 2024
 Reader 0: Yubico YubiKey OTP+FIDO+CCID 00 00
  Event number: 0
  Card state: Card inserted, Exclusive Mode,
  ATR: 3B FD 13 00 00 81 31 FE 15 80 73 C0 21 C0 57 59 75 62 69 4B 65 79 40
```

But "gpg2 --card-status" still does not work.

This command only works if this pcscd.socket is running - and it is only successful if the socket is started about 2 min after booting. The socket which is started at normal boot does not work. The only way to get it working is restarting it after boot.

**Comment by LudovicRousseau** [comment]
I will need more logs to understand what is happening.
Pleased follow https://pcsclite.apdu.fr/#support

**Comment by LudovicRousseau** [comment]
Edit or create the file `/etc/default/pcscd` and add:
```
PCSCD_ARGS=--debug
```
to get debug logs from pcscd started after boot.

See https://blog.apdu.fr/posts/2021/08/pcsc-lite-configuration-using/

**Comment by fansari** [comment]
I have rebooted and ran "gpg2 --card-status".

[log2.txt](https://github.com/user-attachments/files/18083456/log2.txt)

**Comment by LudovicRousseau** [comment]
From your log:
```
Dec 10 18:19:25 bat.localdomain pcscd[2505]: 00000004 ../src/winscard_svc.c:562:ContextThread() CONNECT for client 12, rv=SCARD_E_SHARING_VIOLATION
```

Another application is already using the reader.
Maybe GnuPG could be more explicit in the error message about **why** it failed.

You can use [list_pcsc_applications.sh](https://github.com/LudovicRousseau/PCSC-contrib/blob/master/list_pcsc_applications.sh) to list all the applications using pcsc-lite and find the problematic one.

**Comment by fansari** [comment]
This script gives no output even if I run it as root.

**Comment by LudovicRousseau** [comment]
Exact. I fixed the [list_pcsc_applications.sh](https://github.com/LudovicRousseau/PCSC-contrib/blob/master/list_pcsc_applications.sh) script.
Please try again.

**Comment by fansari** [comment]
I see this after boot:

```
[root@bat bash]# ./list-pcsc-applications.sh
process: /usr/libexec/geoclue (2543)
process: /usr/libexec/gsd-smartcard (3412)
```
After running "gpg2 --card-status" it looks like this:

```
[root@bat bash]# ./list-pcsc-applications.sh
process: /usr/libexec/geoclue (2543)
process: /usr/libexec/gsd-smartcard (3412)
process: scdaemon--multi-server (6790)
```

When I kill the other two processes "gpg2 --card-status" works.

**Comment by LudovicRousseau** [comment]
I think the problem is gnupg2 (scdaemon--multi-server) that requires an exclusive access to the reader (or something similar).

You should report the issue to the GnuPG project, not PCSC.

**Comment by dd9jn** [comment]
Put "pcsc-shared" into ~/.gnupg/scdaemon.conf

```
      --pcsc-shared
              Use shared mode to access the card via PC/SC.  This is a somewhat dangerous option because Scdaemon as‐
              sumes  exclusive access to the card and for example caches certain information from the card.  Use this
              option only if you know what you are doing.
```

As long as you don't change PINs or do other administrative things this works quite well with OpenPGP and PIV cards.  For other cards this option is in general not a problem.  YMMV.

**Comment by fansari** [comment]
I have now these options in my scdaemon.conf:

disable-ccid
pcsc-shared

This "disable-ccid" I had before and now I added "pcsc-shared"

Now it works!

**Comment by LudovicRousseau** [comment]
@fansari @dd9jn I wrote a blog post on this issue https://blog.apdu.fr/posts/2024/12/gnupg-and-pcsc-conflicts-episode-3/

**Comment by LudovicRousseau** [comment]
I rebuilt GnuPG version 1.4.20 (not easy) and I get a different error messge:
```
g10/gpg --card-status
gpg: detected reader `Alcor Micro AU9540 00 00'
gpg: pcsc_connect failed: sharing violation (0x8010000b)
gpg: apdu_send_simple(0) failed: locking failed
Please insert the card and hit return or enter 'c' to cancel: 
```
The error message `pcsc_connect failed: sharing violation (0x8010000b)` was much more explicit at the time.

**Comment by dd9jn** [comment]
On Fri,  3 Oct 2025 13:25, Georg Sauthoff said:

> Under `pcsc-shared` gpg's scdaemon doesn't seem to cache the smart
> card PIN, anymore.

The caching of the PIN is a specila workaround to allow swicthing
between PIV and OpenPGP apps on the fly.  With pcsc-shared we need to
assume that another application is using PIV or OpenPGP and thus we
don't know the PIN state.  It is thus better not to use a cached PIN
which might be wrong.

The application switching (from OpengPGP to PIV and vice versa) clears
the respective VERIFY state and thus a VERIFY command is required.  This
is for what we use the PIN cache.


Shalom-Salam,

   Werner

-- 
The pioneers of a warless world are the youth that
refuse military service.             - A. Einstein
