### ISSUE TITLE
Support of ACR39T-A1

### ISSUE THREAD

**Issue by ijoubert65** [LudovicRousseau/PCSC#218]
Hello,

I try to configure a new USB stick ACR39T-A1 from ACS and I can't make it working with pcsc, it is not recognized : 
pcscd --foreground --debug
 hotplug_libudev.c:297:get_driver() Looking for a driver for VID: 0x072F, PID: 0xB100, path: /dev/bus/usb/001/007
driverSize 349

Here are my version of packages, I am working on an old Linux Debian Jessie:

### Versions

* smart card reader driver name and version : ACR39T-A1
* pcsc-lite version : 
* the output of the command `/usr/sbin/pcscd --version`
* pcsc-lite version 1.8.22.
Copyright (C) 1999-2002 by David Corcoran <corcoran@musclecard.com>.
Copyright (C) 2001-2015 by Ludovic Rousseau <ludovic.rousseau@free.fr>.
Copyright (C) 2003-2004 by Damien Sauveron <sauveron@labri.fr>.
Report bugs to <pcsclite-muscle@lists.alioth.debian.org>.
Enabled features: Linux armv7l-unknown-linux-gnueabihf serial usb libudev usbdropdir=/usr/local/lib/pcsc/drivers ipcdir=/var/run/pcscd configdir=/usr/local/etc/reader.conf.d

### Platform

* Operating system or GNU/Linux distribution name and version : Linux  4.4.13-bone11 #153 Mon Sep 27 12:29:52 CEST 2021 armv7l GNU/Linux
* hatnamectl:
*  Static hostname: XXX
         Icon name: computer
        Machine ID: XXX
           Boot ID: XXX
          Operating System: Debian GNU/Linux 8 (jessie)
            Kernel: Linux 4.4.13-bone11
      Architecture: arm

* Smart card middleware name and version ACR39U ICC Reader 1.10
* Smart card reader manufacturer name and reader model name Advanced Card Systems, Ltd
* Smart card name ACR39T-A1

lsusb -vvv

Bus 001 Device 005: ID 072f:b100 Advanced Card Systems, Ltd
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               1.10
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0
  bDeviceProtocol         0
  bMaxPacketSize0         8
  idVendor           0x072f Advanced Card Systems, Ltd
  idProduct          0xb100
  bcdDevice           30.17
  iManufacturer           1 ACS
  iProduct                2 ACR39U ICC Reader
  iSerial                 0
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           93
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0
    bmAttributes         0x80
      (Bus Powered)
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           3
      bInterfaceClass        11 Chip/SmartCard
      bInterfaceSubClass      0
      bInterfaceProtocol      0
      iInterface              0
      ChipCard Interface Descriptor:
        bLength                54
        bDescriptorType        33
        bcdCCID              1.10  (Warning: Only accurate for version 1.0)
        nMaxSlotIndex           0
        bVoltageSupport         7  5.0V 3.0V 1.8V
        dwProtocols             3  T=0 T=1
        dwDefaultClock       4800
        dwMaxiumumClock      4800
        bNumClockSupported      0
        dwDataRate          12903 bps
        dwMaxDataRate      826000 bps
        bNumDataRatesSupp.      0
        dwMaxIFSD             247
        dwSyncProtocols  00000000
        dwMechanical     00000000
        dwFeatures       000107BA
          Auto configuration based on ATR
          Auto voltage selection
          Auto clock change
          Auto baud rate change
          Auto PPS made by CCID
          CCID can set ICC in clock stop mode
          NAD value other than 0x00 accepted
          Auto IFSD exchange
          TPDU level exchange
        dwMaxCCIDMsgLen       512
        bClassGetResponse    echo
        bClassEnvelope       echo
        wlcdLayout           none
        bPINSupport             0
        bMaxCCIDBusySlots       1
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x02  EP 2 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval              24
Device Status:     0x0000
  (Bus Powered)

### Issue
I was using a stick HID OMNIKEY 6121 and I want to use another one: ACR39T. The old aon was working on my board.
* What do you do?
* What result do you expect?
I can't make ACR39T work becuase it is not recognized by PCSC. It is noted as should work in the list.
* What result do you get instead?
* Just looking for driver:
hotplug_libudev.c:297:get_driver() Looking for a driver for VID: 0x072F, PID: 0xB100, path: /dev/bus/usb/001/007
and no driver found.

I added the file :  99-acr39t.rules

SUBSYSTEM=="usb", ATTR{idVendor}=="072f", ATTR{idProduct}=="b100", MODE="0666", GROUP="plugdev"

It is recognized on usb:
lsusb
Bus 001 Device 007: ID 072f:b100 Advanced Card Systems, Ltd

In syslog:

Feb  1 09:53:15 SA3_MAITRE kernel: [ 6912.405470] usb 1-1: new full-speed USB device number 8 using musb-hdrc
Feb  1 09:53:15 SA3_MAITRE kernel: [ 6912.548208] usb 1-1: New USB device found, idVendor=072f, idProduct=b100
Feb  1 09:53:15 SA3_MAITRE kernel: [ 6912.548227] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
Feb  1 09:53:15 SA3_MAITRE kernel: [ 6912.548236] usb 1-1: Product: ACR39U ICC Reader
Feb  1 09:53:15 SA3_MAITRE kernel: [ 6912.548244] usb 1-1: Manufacturer: ACS
Feb  1 09:53:15 SA3_MAITRE kernel: [ 6912.548756] usb 1-1: Device is not authorized for usage
Feb  1 09:53:15 SA3_MAITRE kernel: [ 6912.609547] usb 1-1: authorized to connect

### Log

Then you shall generate a complete log (do not truncate it).

* If you need to enter the smart card PIN to reproduce the problem then
  consider changing your PIN before generating the logs as the PIN value
  will be included in the logs.
* Kill any running pcscd process
* (re)start pcscd exactly as described bellow:
```
sudo LIBCCID_ifdLogLevel=0x000F pcscd --foreground --debug --apdu --color | tee log.txt
```
* Stop pcscd (using Control-C) after the problem occurred and send me the
  generated log.txt file

See also https://pcsclite.apdu.fr/#support

The content of log.txt:
00000000 debuglog.c:289:DebugLogSetLevel() debug level=debug
00001249 debuglog.c:310:DebugLogSetCategory() Debug options: APDU
00000398 pcscdaemon.c:350:main() Force colored logs
00001232 configfile.l:361:DBGetReaderList() Parsing conf file: /usr/local/etc/reader.conf.d
00004484 pcscdaemon.c:658:main() pcsc-lite 1.8.22 daemon ready.
00025294 hotplug_libudev.c:297:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0002, path: /dev/bus/usb/001/001
driverSize 349
00005115 hotplug_libudev.c:297:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0002, path: /dev/bus/usb/001/001
driverSize 349
00009210 hotplug_libudev.c:297:get_driver() Looking for a driver for VID: 0x072F, PID: 0xB100, path: /dev/bus/usb/001/007

Thank you!

**Comment by LudovicRousseau** [comment]
You need to use the CCID driver version 1.4.19 or more.
https://ccid.apdu.fr/ccid/shouldwork.html#0x072F0xB100

**Comment by ijoubert65** [comment]
Thank you.
Version of  libccid is in the debian package:
iU  libccid                                1.4.34-1                                                armhf        PC/SC driver for USB CCID smart card readers

**Comment by LudovicRousseau** [comment]
Problem fixed.

**Comment by ijoubert65** [comment]
As I use 1.4.34 libccid the problem musnt't occur.

**Comment by LudovicRousseau** [comment]
You are using pcsc-lite 1.8.22 which is VERY old (released in 2017).
I doubt you are really using CCID version 1.4.34 (from 2021).

You are using Debian 8 Jessie released in 2018.
Upgrade your system and it should work.

**Comment by LudovicRousseau** [comment]
You need to upgrade CCID only.

**Comment by LudovicRousseau** [comment]
The Debian package name is libccid
https://packages.debian.org/search?keywords=libccid

I think you will have to backport version 1.4.19 (or more) to Jessie.

**Comment by ijoubert65** [comment]
Thank you very much, I will try it.

**Comment by ijoubert65** [comment]
So I installed the 1.4.34-1 version found here : http://ftp.debian.org/debian/pool/main/c/ccid/ but the problem remains.

**Comment by LudovicRousseau** [comment]
Generate a pcscd log trace. See https://ccid.apdu.fr/#support

**Comment by ijoubert65** [comment]
Thank you for the answer.

Here is the content of log.txt,  I unplugged then plugged the stick ACR39t-A1( VID: 0x072F, PID: 0xB100) and then killed the process.

00000000 debuglog.c:289:DebugLogSetLevel() debug level=debug
00009341 debuglog.c:310:DebugLogSetCategory() Debug options: APDU
00000399 pcscdaemon.c:350:main() Force colored logs
00000517 utils.c:82:GetDaemonPid() Can't open /var/run/pcscd/pcscd.pid: No such file or directory
00001181 configfile.l:361:DBGetReaderList() Parsing conf file: /usr/local/etc/reader.conf.d
00000866 pcscdaemon.c:658:main() pcsc-lite 1.8.22 daemon ready.
00026386 hotplug_libudev.c:297:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0002, path: /dev/bus/usb/001/001
driverSize 349
00002070 hotplug_libudev.c:297:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0002, path: /dev/bus/usb/001/001
driverSize 349
00009090 hotplug_libudev.c:297:get_driver() Looking for a driver for VID: 0x072F, PID: 0xB100, path: /dev/bus/usb/001/002
driverSize 349
13901338 hotplug_libudev.c:651:HPEstablishUSBNotifications() USB Device removed
23002010 hotplug_libudev.c:657:HPEstablishUSBNotifications() USB Device add
00002092 hotplug_libudev.c:297:get_driver() Looking for a driver for VID: 0x072F, PID: 0xB100, path: /dev/bus/usb/001/003
driverSize 349
17004363 pcscdaemon.c:191:signal_thread() Received signal: 2
00000046 pcscdaemon.c:224:signal_thread() Preparing for suicide
00001781 hotplug_libudev.c:719:HPStopHotPluggables() Hotplug stopped
01000145 readerfactory.c:1352:RFCleanupReaders() entering cleaning function
00000088 winscard_svc.c:155:ContextsDeinitialize() remaining threads: 0
00000020 pcscdaemon.c:779:at_exit() cleaning /var/run/pcscd

Thank you for the help.

**Comment by LudovicRousseau** [comment]
What is the output of `pcscd --version`?

**Comment by ijoubert65** [comment]
Here s is the result:
pcscd --version
pcsc-lite version 1.8.22.
Copyright (C) 1999-2002 by David Corcoran <corcoran@musclecard.com>.
Copyright (C) 2001-2015 by Ludovic Rousseau <ludovic.rousseau@free.fr>.
Copyright (C) 2003-2004 by Damien Sauveron <sauveron@labri.fr>.
Report bugs to <pcsclite-muscle@lists.alioth.debian.org>.
Enabled features: Linux armv7l-unknown-linux-gnueabihf serial usb libudev usbdropdir=/usr/local/lib/pcsc/drivers ipcdir=/var/run/pcscd configdir=/usr/local/etc/reader.conf.d

**Comment by LudovicRousseau** [comment]
I see it is a local recompilation. It is not the Debian Jessie package.
It will **not** work with a CCID driver package from Debian.

**Comment by ijoubert65** [comment]
With dpkg, we can see:
dpkg -l | grep pcsc
ii  libpcsc-perl                           1.4.13-1+b2                                             armhf        Perl interface to the PC/SC smart card library
ii  libpcsclite1:armhf                     1.8.13-1+deb8u1                                         armhf        Middleware to access a smart card using PC/SC (library)
iU  pcsc-tools                             1.4.23-1                                                armhf        Some tools to use with smart cards and PC/SC
rc  pcscd                                  **1.8.13-1+deb8u1**                                         armhf        Middleware to access a smart card using PC/SC (daemon side)
But I don't really know how it had been generated. 
I will try with the 1.8.24 version

**Comment by LudovicRousseau** [comment]
The pcscd Debian package version 1.8.13 as been **removed**.

You have your locally built pcsc-lite version 1.8.22 installed in `/usr/local/`.

I suggest you to redo your complete system with a recent Debian version.
Or I can do consulting. Contact me by email https://blog.apdu.fr/articles/about_me/

**Comment by ijoubert65** [comment]
Thank you for the help.
I installed these packages:

ii  libpcsclite1:armhf               1.8.24-1          armhf        Middleware to access a smart card using PC/SC (library)
ii  pcscd                                  1.8.24-1          armhf        Middleware to access a smart card using PC/SC (d      
ii  libccid                                1.4.34-1          armhf        PC/SC driver for USB CCID smart card readers

And now ACR39T is seen:

00000000 debuglog.c:299:DebugLogSetLevel() debug level=debug
00015545 debuglog.c:320:DebugLogSetCategory() Debug options: APDU
00000390 [-1224925184] pcscdaemon.c:352:main() Force colored logs
00000551 [-1224925184] utils.c:82:GetDaemonPid() Can't open /var/run/pcscd/pcscd.pid: No such file or directory
00000840 [-1224925184] configfile.l:284:DBGetReaderListDir() Parsing conf directory: /etc/reader.conf.d
00000549 [-1224925184] configfile.l:360:DBGetReaderList() Parsing conf file: /etc/reader.conf.d/libccidtwin.dpkg-old
00000768 [-1224925184] configfile.l:321:DBGetReaderListDir() Skipping non regular file: ..
00000476 [-1224925184] configfile.l:321:DBGetReaderListDir() Skipping non regular file: .
00000340 [-1224925184] configfile.l:360:DBGetReaderList() Parsing conf file: /etc/reader.conf.d/libccidtwin
00000489 [-1224925184] pcscdaemon.c:662:main() pcsc-lite 1.8.24 daemon ready.
00034913 [-1224925184] hotplug_libudev.c:297:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0002, path: /dev/bus/usb/001/001
00002136 [-1224925184] hotplug_libudev.c:297:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0002, path: /dev/bus/usb/001/001
00001983 [-1224925184] hotplug_libudev.c:297:get_driver() Looking for a driver for VID: 0x072F, PID: 0xB100, path: /dev/bus/usb/001/002
00000780 [-1224925184] hotplug_libudev.c:436:HP**AddDevice() Adding USB device: ACS ACR39U ICC Reader**
00000914 [-1224925184] readerfactory.c:1075:RFInitializeReader() Attempting startup of ACS ACR39U ICC Reader 00 00 using /usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/                                                                     Linux/libccid.so
00001948 [-1224925184] readerfactory.c:950:RFBindFunctions() Loading IFD Handler 3.0
00001080 [-1224925184] ifdhandler.c:2025:init_driver() Driver version: 1.4.34
00005751 [-1224925184] ifdhandler.c:2042:init_driver() LogLevel: 0x0003
00006026 [-1224925184] ifdhandler.c:2053:init_driver() DriverOptions: 0x0000
00010742 [-1224925184] ifdhandler.c:2066:init_driver() LogLevel from LIBCCID_ifdLogLevel: 0x000F
00000669 [-1224925184] ifdhandler.c:110:CreateChannelByNameOrChannel() Lun: 0, device: usb:072f/b100:libudev:0:/dev/bus/usb/001/002
00000344 [-1224925184] ccid_usb.c:237:OpenUSBByName() Reader index: 0, Device: usb:072f/b100:libudev:0:/dev/bus/usb/001/002
00000353 [-1224925184] ccid_usb.c:269:OpenUSBByName() interface_number: 0
00000301 [-1224925184] ccid_usb.c:270:OpenUSBByName() usb bus/device: 1/2
00000276 [-1224925184] ccid_usb.c:302:OpenUSBByName() Using: /usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Info.plist
00004871 [-1224925184] ccid_usb.c:320:OpenUSBByName() ifdManufacturerString: Ludovic Rousseau (ludovic.rousseau@free.fr)
00011817 [-1224925184] ccid_usb.c:321:OpenUSBByName() ifdProductString: Generic CCID driver
00000389 [-1224925184] ccid_usb.c:322:OpenUSBByName() Copyright: This driver is protected by terms of the GNU Lesser General Public License version 2.1, or (at your opt                                                                     ion) any later version.
00008548 [-1224925184] ccid_usb.c:406:OpenUSBByName() Try device: 1/2
00001042 [-1224925184] ccid_usb.c:416:OpenUSBByName() vid/pid : 072F/B100
00000371 [-1224925184] ccid_usb.c:482:OpenUSBByName() Checking device: 1/2
00000325 [-1224925184] ccid_usb.c:553:OpenUSBByName() Trying to open USB bus/device: 1/2
00189822 [-1224925184] ccid_usb.c:659:OpenUSBByName() Found Vendor/Product: 072F/B100 (ACS ACR39U ICC Reader)
00000980 [-1224925184] ccid_usb.c:661:OpenUSBByName() Using USB bus/device: 1/2
00000369 [-1224925184] ccid_usb.c:722:OpenUSBByName() bNumDataRatesSupported is 0
00009601 [-1224925184] ccid_usb.c:1328:InterruptRead() before (0), timeout: 100 ms
00053379 [-1224925184] ccid_usb.c:1374:InterruptRead() after (0) (0)
00000805 [-1224925184] NotifySlotChange: 50 03
00000430 [-1224925184] -> 000000 65 00 00 00 00 00 00 00 00 00
03000753 [-1224925184] ccid_usb.c:897:ReadUSB() read failed (1/2): -7 LIBUSB_ERROR_TIMEOUT
00000756 [-1224925184] -> 000000 65 00 00 00 00 00 01 00 00 00
00000790 [-1224925184] <- 000000 81 00 00 00 00 00 01 01 00 01
00000440 [-1224925184] ifdhandler.c:388:IFDHGetCapabilities() tag: 0xFB3, usb:072f/b100:libudev:0:/dev/bus/usb/001/002 (lun: 0)
00000366 [-1224925184] readerfactory.c:396:RFAddReader() Using the reader polling thread
00000318 [-1224925184] ifdhandler.c:1885:IFDHICCPresence() usb:072f/b100:libudev:0:/dev/bus/usb/001/002 (lun: 0)
00000370 [-1224925184] -> 000000 65 00 00 00 00 00 02 00 00 00
00010453 [-1224925184] <- 000000 81 00 00 00 00 00 02 01 00 01
00000415 [-1224925184] ifdhandler.c:2005:IFDHICCPresence() Card present
00000581 [-1224925184] ifdhandler.c:388:IFDHGetCapabilities() tag: 0xFAE, usb:072f/b100:libudev:0:/dev/bus/usb/001/002 (lun: 0)
00000443 [-1224925184] ifdhandler.c:484:IFDHGetCapabilities() Reader supports 1 slot(s)
00000663 [-1224925184] readerfactory.c:1410:RFWaitForReaderInit() Waiting init for reader: ACS ACR39U ICC Reader 00 00
00000519 [-1245478016] ifdhandler.c:1885:IFDHICCPresence() usb:072f/b100:libudev:0:/dev/bus/usb/001/002 (lun: 0)
00000491 [-1245478016] -> 000000 65 00 00 00 00 00 03 00 00 00
00007054 [-1245478016] <- 000000 81 00 00 00 00 00 03 01 00 01
00000454 [-1245478016] ifdhandler.c:2005:IFDHICCPresence() Card present
00000341 [-1245478016] ifdhandler.c:1885:IFDHICCPresence() usb:072f/b100:libudev:0:/dev/bus/usb/001/002 (lun: 0)
00000415 [-1245478016] -> 000000 65 00 00 00 00 00 04 00 00 00
00000686 [-1245478016] <- 000000 81 00 00 00 00 00 04 01 00 01
00000473 [-1245478016] ifdhandler.c:2005:IFDHICCPresence() Card present
00000175 [-1224925184] readerfactory.c:1410:RFWaitForReaderInit() Waiting init for reader: ACS ACR39U ICC Reader 00 00
00000603 [-1245478016] ifdhandler.c:1183:IFDHPowerICC() action: PowerUp, usb:072f/b100:libudev:0:/dev/bus/usb/001/002 (lun: 0)
00000321 [-1245478016] -> 000000 62 00 00 00 00 00 05 00 00 00
00009455 [-1224925184] readerfactory.c:1410:RFWaitForReaderInit() Waiting init for reader: ACS ACR39U ICC Reader 00 00
00010129 [-1224925184] readerfactory.c:1410:RFWaitForReaderInit() Waiting init for reader: ACS ACR39U ICC Reader 00 00
00010118 [-1224925184] readerfactory.c:1410:RFWaitForReaderInit() Waiting init for reader: ACS ACR39U ICC Reader 00 00
00010114 [-1224925184] readerfactory.c:1410:RFWaitForReaderInit() Waiting init for reader: ACS ACR39U ICC Reader 00 00
00010118 [-1224925184] readerfactory.c:1410:RFWaitForReaderInit() Waiting init for reader: ACS ACR39U ICC Reader 00 00
00010116 [-1224925184] readerfactory.c:1410:RFWaitForReaderInit() Waiting init for reader: ACS ACR39U ICC Reader 00 00
00003057 [-1245478016] <- 000000 80 1C 00 00 00 00 05 00 00 00 3B DF 18 FF 81 F1 FE 43 00 3F 03 83 4D 49 46 41 52 45 20 50 6C 75 73 20 53 41 4D 3B
00000368 [-1245478016] eventhandler.c:289:EHStatusHandlerThread() powerState: POWER_STATE_POWERED
00000339 [-1245478016] Card ATR: 3B DF 18 FF 81 F1 FE 43 00 3F 03 83 4D 49 46 41 52 45 20 50 6C 75 73 20 53 41 4D 3B
00000135 [-1245478016] ifdhandler.c:1885:IFDHICCPresence() usb:072f/b100:libudev:0:/dev/bus/usb/001/002 (lun: 0)
00000112 [-1245478016] -> 000000 65 00 00 00 00 00 06 00 00 00
00000743 [-1245478016] <- 000000 81 00 00 00 00 00 06 00 00 00
00000470 [-1245478016] ifdhandler.c:2005:IFDHICCPresence() Card present
00000154 [-1245478016] ifdhandler.c:317:IFDHPolling() usb:072f/b100:libudev:0:/dev/bus/usb/001/002 (lun: 0) 5000 ms
00000168 [-1245478016] ccid_usb.c:1328:InterruptRead() before (0), timeout: 5000 ms
05000391 [-1245478016] ccid_usb.c:1374:InterruptRead() after (0) (2)
00000600 [-1245478016] ifdhandler.c:1885:IFDHICCPresence() usb:072f/b100:libudev:0:/dev/bus/usb/001/002 (lun: 0)
00000052 [-1245478016] -> 000000 65 00 00 00 00 00 07 00 00 00
01787121 [-1228455040] pcscdaemon.c:193:signal_thread() Received signal: 2
00000046 [-1228455040] pcscdaemon.c:226:signal_thread() Preparing for suicide
00002094 [-1224925184] hotplug_libudev.c:713:HPStopHotPluggables() Hotplug stopped
01000160 [-1224925184] readerfactory.c:1353:RFCleanupReaders() entering cleaning function
00000063 [-1224925184] readerfactory.c:1362:RFCleanupReaders() Stopping reader: ACS ACR39U ICC Reader 00 00
00000022 [-1224925184] readerfactory.c:610:RFRemoveReader() UnrefReader() count was: 1
00000018 [-1224925184] eventhandler.c:175:EHDestroyEventHandler() Stomping thread.
00210868 [-1245478016] ccid_usb.c:897:ReadUSB() read failed (1/2): -7 LIBUSB_ERROR_TIMEOUT
00000264 [-1245478016] ifdwrapper.c:364:IFDStatusICC() Card not transacted: 612
00000030 [-1245478016] eventhandler.c:482:EHStatusHandlerThread() powerState: POWER_STATE_UNPOWERED
00000131 [-1224925184] ifdhandler.c:388:IFDHGetCapabilities() tag: 0xFB1, usb:072f/b100:libudev:0:/dev/bus/usb/001/002 (lun: 0)
00000149 [-1224925184] ifdhandler.c:388:IFDHGetCapabilities() tag: 0xFB2, usb:072f/b100:libudev:0:/dev/bus/usb/001/002 (lun: 0)
00000019 [-1224925184] eventhandler.c:200:EHDestroyEventHandler() Request stopping of polling thread
00000016 [-1224925184] ifdhandler.c:353:IFDHStopPolling() usb:072f/b100:libudev:0:/dev/bus/usb/001/002 (lun: 0)
00000200 [-1245478016] eventhandler.c:504:EHStatusHandlerThread() Die
00000253 [-1224925184] eventhandler.c:215:EHDestroyEventHandler() Thread stomped.
00000027 [-1224925184] readerfactory.c:1126:RFUnInitializeReader() Attempting shutdown of ACS ACR39U ICC Reader 00 00.
00000021 [-1224925184] ifdhandler.c:291:IFDHCloseChannel() usb:072f/b100:libudev:0:/dev/bus/usb/001/002 (lun: 0)
00000031 [-1224925184] -> 000000 63 00 00 00 00 00 08 00 00 00
00001327 [-1224925184] <- 000000 81 00 00 00 00 00 08 01 00 01
00000052 [-1224925184] ccid_usb.c:940:CloseUSB() Closing USB device: 1/2
00000019 [-1224925184] ccid_usb.c:952:CloseUSB() Last slot closed. Release resources
00000128 [-1224925184] ccid_usb.c:189:close_libusb_if_needed() libusb_exit
00006294 [-1224925184] readerfactory.c:987:RFUnloadReader() Unloading reader driver.
00000265 [-1224925184] winscard_svc.c:155:ContextsDeinitialize() remaining threads: 0
00000031 [-1224925184] pcscdaemon.c:785:at_exit() cleaning /var/run/pcscd

Thank you for your patience and happy new year!
