### ISSUE TITLE
Can pcsc-lite run standalone (without pcscd)?

### ISSUE THREAD

**Issue by JonasVautherin** [LudovicRousseau/PCSC#219]
I am trying to run PCSC on Android, and I am receiving the error `SCARD_E_NO_SERVICE` ("The Smart card resource manager is not running").

What is this resource manager? Is it something that is expected to be running on the host (here Android), or could it mean that it cannot talk to the smart card at all (it may hint that I failed to get the USB permission on Android)?

I am not completely aware of how PCSC works, but on Linux I have a daemon running (pcscd). Obviously I cannot run it on Android, so I am hoping that PCSC does not necessarily require the daemon?

**Comment by JonasVautherin** [comment]
Seems like it means that the daemon is not running. On Linux, if I stop the daemon and try to establish a context, I receive the same message.

So my question is actually: can pcsc-lite run standalone, without pcscd?

**Comment by JonasVautherin** [comment]
I have spend some hours investigating, and running pcsc on Android does not seem trivial (I tried to cross-compile and run it and it seems like it depends on Linux drivers).

**Comment by FeitianSmartcardReader** [comment]
@JonasVautherin if you just want to call PC/SC API, maybe you can try our lib.
https://github.com/FeitianSmartcardReader/FEITIAN_MOBILE_READERS/tree/master/Android_SDK/new_android_sdk/PCSC_API

**Comment by LudovicRousseau** [comment]
@JonasVautherin you can also have a look at "Secure Element Evaluation Kit for the Android platform"
https://seek-for-android.github.io/
