### ISSUE TITLE
move pcsc-spy file from HOME

### ISSUE THREAD

**Issue by mattia-b89** [LudovicRousseau/PCSC#23]
I'd like to see an option to put `pcsc-spy` file in other path than $HOME.
I mean the file created by the `pcsc-spy` command

**Comment by LudovicRousseau** [comment]
What do you want to propose exactly?

**Comment by mattia-b89** [comment]
a) a switch for that command
b) a config file in which specify the path

**Comment by LudovicRousseau** [comment]
The problem is that `libpcscspy.so`` and ``pcsc-spy`` need to use the same file.
I don't want to create a configuration file just for that.
I was thinking about using an environment variable.

What is your use case?

**Comment by mattia-b89** [comment]
I'm a simple user and I don't want that file in my home

**Comment by LudovicRousseau** [comment]
So just remove it and do not use pcsc-spy.

**Comment by mattia-b89** [comment]
another option is: call it ".pcsp-spy", so it is not visible

**Comment by LudovicRousseau** [comment]
If the problem is that the file is visible in your home directory then just uninstall the spy mechanism (so the file is not re-created again) and remove the ``~/pcsp-spy`` file.

**Comment by mattia-b89** [comment]
> uninstall the spy mechanism (so the file is not re-created again)
what do you mean?
in my case, that file is created every time I launch `pcsc-spy`

**Comment by LudovicRousseau** [comment]
Exact.
If you start ``pcsc-spy`` then the file is created.
If you spy PCSC then you are not a "simple user".
I do not understand your real motivations.
