### ISSUE TITLE
Build pcscd error

### ISSUE THREAD

**Issue by FeitianSmartcardReader** [LudovicRousseau/PCSC#25]
Hi Ludovic

I do build pcscd and found some error:
root@ubuntu:/opt/software/pcscd/PCSC# ./configure CC=/opt/freescale/usr/local/gcc-4.6.2-glibc-2.13-linaro-multilib-2011.12/fsl-linaro-toolchain/bin/arm-fsl-linux-gnueabi-gcc --host=arm-fsl-linux prefix=/usr/ccid --enable-libusb LIBUSB_LIBS="-L/usr/ccid/install/lib -lusb-1.0" LIBUSB_CFLAGS="-I/usr/ccid/install/include/libusb-1.0" PCSC_CFLAGS="-I/usr/ccid/include/PCSC" PCSC_LIBS="-L/usr/ccid/lib/ -lpcsclite" --enable-usbdropdir="/usr/ccid/lib/pcsc/drivers" --enable-static --disable-libudev --disable-libsystemd

**After, do make, got below error:**
root@ubuntu:/opt/software/pcscd/PCSC# make
make  all-recursive
make[1]: Entering directory `/opt/software/pcscd/PCSC'
Making all in src
make[2]: Entering directory `/opt/software/pcscd/PCSC/src'
Making all in spy
make[3]: Entering directory `/opt/software/pcscd/PCSC/src/spy'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/opt/software/pcscd/PCSC/src/spy'
make[3]: Entering directory `/opt/software/pcscd/PCSC/src'
  CCLD     pcsc-wirecheck
pcsc-wirecheck-main.o: In function `main':
/opt/software/pcscd/PCSC/src/pcsc-wirecheck-main.c:12: undefined reference to `pcsc_assert_wire_constants'
collect2: ld returned 1 exit status
make[3]: *** [pcsc-wirecheck] Error 1
make[3]: Leaving directory `/opt/software/pcscd/PCSC/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/opt/software/pcscd/PCSC/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/opt/software/pcscd/PCSC'
make: *** [all] Error 2
root@ubuntu:/opt/software/pcscd/PCSC# 

**I do comment that line, then can build successful**

There have two issues:
1. Build got /opt/software/pcscd/PCSC/src/pcsc-wirecheck-main.c:12: undefined reference to `pcsc_assert_wire_constants'
2. Download package from release, build give configfile.c missing

**Comment by LudovicRousseau** [comment]
``pcsc_assert_wire_constants`` is defined in ``pcsc-wirecheck-dist.c`` generated by ``pcsc-wirecheck-gen``.

What is the result of:
```
$ make pcsc-wirecheck-dist.c
```

**Comment by FeitianSmartcardReader** [comment]
strange, the pcsc-wirecheck-dist.c is empty, no any code.

root@ubuntu:/opt/software/package/ccid/CCID/PCSC/src# cat pcsc-wirecheck-dist.c root@ubuntu:/opt/software/package/ccid/CCID/PCSC/src# make pcsc-wirecheck-dist.cmake: `pcsc-wirecheck-dist.c' is up to date.
root@ubuntu:/opt/software/package/ccid/CCID/PCSC/src#

**Comment by LudovicRousseau** [comment]
Remove the file ``pcsc-wirecheck-dist.c`` and run ``make pcsc-wirecheck-dist.c`` again.

**Comment by FeitianSmartcardReader** [comment]
root@ubuntu:/opt/software/package/ccid/CCID/PCSC/src# make pcsc-wirecheck-dist.c  CC       pcsc-wirecheck-gen.o
  CCLD     pcsc-wirecheck-gen
rm -f pcsc-wirecheck-dist.c
./pcsc-wirecheck-gen > pcsc-wirecheck-dist.c.tmp
/bin/bash: line 7: ./pcsc-wirecheck-gen: cannot execute binary file
mv pcsc-wirecheck-dist.c.tmp pcsc-wirecheck-dist.c
root@ubuntu:/opt/software/package/ccid/CCID/PCSC/src#

**Comment by FeitianSmartcardReader** [comment]
**Another strange issue is below**
I if comment that line, I can build successful on embed linux, but it has issue for multi-slot reader support, then I want do test under Ubuntu, build pcsc source code under ubuntu, I found another issue.
I am using same command to build, put all related file under /usr/ccid
**_libusb build with no error_**
**_build pcsc got error below_** 
If I using below command, it can build without error:
`./configure CC=/opt/freescale/usr/local/gcc-4.6.2-glibc-2.13-linaro-multilib-2011.12/fsl-linaro-toolchain/bin/arm-fsl-linux-gnueabi-gcc --host=arm-fsl-linux prefix=/usr/ccid --enable-libusb LIBUSB_LIBS="-L/usr/ccid/install/lib -lusb-1.0" LIBUSB_CFLAGS="-I/usr/ccid/install/include/libusb-1.0" PCSC_CFLAGS="-I/usr/ccid/include/PCSC" PCSC_LIBS="-L/usr/ccid/lib/ -lpcsclite" --enable-usbdropdir="/usr/ccid/lib/pcsc/drivers" --enable-static --disable-libudev --disable-libsystemd`

**But if replacement to ubuntu local gcc, it give error:**
`./configure CC=/usr/bin/gcc --host=arm-fsl-linux prefix=/usr/ccid --enable-libusb LIBUSB_LIBS="-L/usr/ccid/install/lib -lusb-1.0" LIBUSB_CFLAGS="-I/usr/ccid/install/include/libusb-1.0" PCSC_CFLAGS="-I/usr/ccid/include/PCSC" PCSC_LIBS="-L/usr/ccid/lib/ -lpcsclite" --enable-usbdropdir="/usr/ccid/lib/pcsc/drivers" --enable-static --disable-libudev --disable-libsystemd`


checking libusb.h usability... yes
checking libusb.h presence... yes
checking for libusb.h... yes
checking for libusb_init... configure: error: libusb not found, use ./configure LIBUSB_LIBS=...
**root@ubuntu:/opt/software/package/test/PCSC# pkg-config --libs libusb-1.0
-L/usr/local/lib -lusb-1.0**  
root@ubuntu:/opt/software/package/test/PCSC#

**Comment by LudovicRousseau** [comment]
I understand the problem.
``pcsc-wirecheck-gen`` is cross compiled for ARM but is executed on the x86 system.

You an avoid the problem by creating an empty ``pcsc-wirecheck`` file.

**Comment by FeitianSmartcardReader** [comment]
Add comments:
When I do install pcsc and I found it always give below error
`checking for libusb_init... configure: error: libusb not found, use ./configure LIBUSB_LIBS=...`
after check config.log, I saw there have error 
`/usr/ccid/lib/libusb-1.0.so: undefined reference to `clock_gettime'`
To sovle this issue, will need do build with -lrt:
`./configure CC=/opt/arm-2014.05/bin/arm-none-linux-gnueabi-gcc --host=arm-none-linux --prefix=/usr/ccid --prefix=/usr/ccid --enable-libusb LIBUSB_LIBS="-L/usr/ccid/lib/ -lusb-1.0 -lrt" LIBUSB_CFLAGS="-I/usr/ccid/include/libusb-1.0" PCSC_CFLAGS="-I/usr/ccid/include/PCSC" PCSC_LIBS="-L/usr/ccid/lib/ -lpcsclite" --enable-usbdropdir="/usr/ccid/lib/pcsc/drivers"`

**Comment by LudovicRousseau** [comment]
The files ``pcsc-wirecheck-dist.c``, ``pcsc-wirecheck-gen.c`` and ``pcsc-wirecheck-main.c`` are provide in the ``.tar.bz2`` archive.
If you really want to use the source code from git and do cross-compilation you should generate the missing ``.c`` files first.
