### ISSUE TITLE
Connect to smart card reader problem with Php

### ISSUE THREAD

**Issue by MuminCelal** [LudovicRousseau/PCSC#27]
I am trying to run PCSC PHP code that you write but I am getting error. I got the code from your website.

> Warning: scard_list_readers() expects parameter 1 to be resource, boolean given in /var/www/html/pcsc.php on line 8
Using reader: 
Warning: scard_connect() expects parameter 1 to be resource, boolean given in /var/www/html/pcsc.php on line 16
Warning: scard_release_context() expects parameter 1 to be resource, boolean given in /var/www/html/pcsc.php on line 31

I do not know how to solve these problems.

**Comment by LudovicRousseau** [comment]
You should contact the author (not me) of the PCSC wrapper in PHP.
