### ISSUE TITLE
When used both pcscd and libnfc, the Buzzer and LED desn't work on acr122u-a9 at Raspberry-pi 2 with Raspbian. 

### ISSUE THREAD

**Issue by comseong** [LudovicRousseau/PCSC#3]
I installed both pcscd and acsccid. Since I have started the pcscd manually by "service pcscd start" command, the Buzzer and LED work well when I tagged a card. But when I use the nfc-tool command like nfc-list or lsnfc, commands work well but the Buzzer and LED doesn't work again even though the pcscd is running on the memory. Can't I use both the pcscd and libnfc at the same time?

**Comment by LudovicRousseau** [comment]
libnfc does not (in general) use pcsc-lite. They may conflict.

**Comment by SebLeKlatz** [comment]
bonjour Ludovic, je ne comprends pas, dans tous les tutos que je lis, on me demande d'installer pcsc et libnfc.
En désinstallant pcsc les cartes ne sont plus du tout reconnues.
j'ai pourtant bien : 
`pi@raspberrypi:~ $ sudo nfc-list
nfc-list uses libnfc 1.7.1
NFC device: ACS / ACR122U PICC Interface opened
`  
en remettant pcsc, je me retrouve avec mon problème de cartes parfois reconnues parfois non, dans tous les cas avec LED éteinte.

si tu trouves 2mn pour me donner une piste où 2 je t'en serais très reconnaissant

pour info: RASPBERRY PI-3 B rev 1.2 Linux Stretch

merci!

**Comment by LudovicRousseau** [comment]
From http://nfc-tools.org/index.php?title=Libnfc#Installation

> Because some dependencies (e.g. libusb and optionnal PCSC-Lite)...

Contact the libnfc project for help.

**Comment by SebLeKlatz** [comment]
ok thanks but in the debian section, after the command, `sudo git fetch anonscm` I have :
`fatal: unable to connect to anonscm.debian.org:
anonscm.debian.org[0: 2001:648:2ffc:deb::211:202]: errno=Connexion refusée
anonscm.debian.org[1: 194.177.211.202]: errno=Connexion refusée
`
maybe I have to uninstall first the version of libnfc already installed

I try that

**Comment by SebLeKlatz** [comment]
oops!!
`anonscm.debian.org has migrated to salsa.debian.org! #39927
`

**Comment by SebLeKlatz** [comment]
I don't understand, the reader see the card, but the LED is off and I can't manage to include the card on jeedom

`pi@raspberrypi:~/libnfc-1.7.0-rc7 $ sudo nfc-list
nfc-list uses libnfc 1.7.0-rc7
NFC device: ACS / ACR122U PICC Interface opened
1 ISO14443A passive target(s) found:
ISO/IEC 14443A (106 kbps) target:
    ATQA (SENS_RES): 00  04  
       UID (NFCID1): 06  af  b5  12  
      SAK (SEL_RES): 08  `

what can I do please??

thanks

**Comment by LudovicRousseau** [comment]
contact libnfc project for libnfc issues.

**Comment by nono13500** [comment]
Même pb que Seb. L interface est ouverte mais la lumière est éteinte...
