### ISSUE TITLE
drivers aren't available at given location

### ISSUE THREAD

**Issue by sh-dvl** [LudovicRousseau/PCSC#37]
in DRIVERS you write:

To install USB drivers, download the driver from http://musclecard.com/software.html

but that url leads to an empty page.

is there any other location?

**Comment by LudovicRousseau** [comment]
I removed the outdated file. Thanks.

You can find drivers at https://muscle.apdu.fr/musclecard.com/sourcedrivers.html but this page is really old.
Your best option is https://ccid.apdu.fr/
