### ISSUE TITLE
Leaking sockets

### ISSUE THREAD

**Issue by MartinN-n** [LudovicRousseau/PCSC#50]
Hello,

it seems libpcsc is leaking sockets if connection is dropped by e.g. polkit. From my (brief) investigation, while socket is created in `ClientSetupSession()` called from `SCardEstablishContextTH()`, resulting socket in `dwClientID` is not stored in context until the end of this session, while you can exit on e.g. `MessageReceive()` failure in the very next block after `ClientSetupSession()`.
This leads to growing number of open files, should the application repeatedly try to call `SCardEstablishContext()`, and eventually everything explodes...

Did I miss anything?

Thanks,
Martin

**Comment by LudovicRousseau** [comment]
You are right.
Working on a fix.

**Comment by LudovicRousseau** [comment]
Fixed in https://github.com/LudovicRousseau/PCSC/commit/dd34cb3695cfee90e4cc8720446b1116ca19e2d0

Thanks
