### ISSUE TITLE
Using 'select' in libpcsclite can be problematic for application opening a large number of file descriptors

### ISSUE THREAD

**Issue by kamengopin** [LudovicRousseau/PCSC#51]
Hi Ludovic,

Currently, libpcsclite uses **select** + non-blocking IO when communicating to the PCSC daemon.
However, **select** can be used only on file descriptors whose value does not exceed FD_SETSIZE. Quote from Linux man page for **select**:

> fd_set is a fixed size buffer.  Executing FD_CLR() or FD_SET() with a value of fd that is negative or is equal to or larger than FD_SETSIZE will result in undefined behavior.

More often that not, this undefined behavior will come in the form of a stack corruption.

This means that an application which uses libpcsclite is forced to have no more than FD_SETSIZE (1024) open file descriptors at any given moment. Depending on the use-case this limit can be problematic for the application.

There are other I/O event notification mechanisms which do not have this limitation:
poll, epoll on Linux, kqueue on Mac and BSD, IO completion ports on Windows, etc
Have you considered using any of the above?

**Comment by LudovicRousseau** [comment]
Do you plan to propose a patch?
What do you expect from me?

**Comment by kamengopin** [comment]
Yeah, I planned to propose a patch but I am not sure when I will have the time for that (probably after the holidays). For now I just wanted to bring the issue to your attention.

**Comment by LudovicRousseau** [comment]
Fixed in https://github.com/LudovicRousseau/PCSC/commit/20385efba2075d4c13acfea43d0abc8c38d8c106
