### ISSUE TITLE
 Can not find the RFID reader

### ISSUE THREAD

**Issue by Demso-alex** [LudovicRousseau/PCSC#64]
Hello ! 
 Can not find the RFID reader on pcsc_scan =>
![screen_pcsc_scan](https://user-images.githubusercontent.com/51439706/59020571-8a413f00-884a-11e9-80c7-3ba5726e215b.png)

It is sure that the RFID reader works because I have already run on a raspberry with PCSC
(but here I am not on a raspberry)

But the reader is found with lsusb =>
Bus 001 Device 020: ID 072f:2224 Advanced Card Systems, Ltd ACR1281 1S Dual Reader

I tried too https://ludovicrousseau.blogspot.com/2013/11/linux-nfc-driver-conflicts-with-ccid.html
But it does not work.

Someone can help me ? 
thank you in advance

have a nice day

Versions

ccid-1.4.29-1 (libccid)
reader ACR1281U
/usr/sbin/pcscd --version =>
pcsc-lite version 1.8.23.
Copyright (C) 1999-2002 by David Corcoran <corcoran@musclecard.com>.
Copyright (C) 2001-2015 by Ludovic Rousseau <ludovic.rousseau@free.fr>.
Copyright (C) 2003-2004 by Damien Sauveron <sauveron@labri.fr>.
Report bugs to <pcsclite-muscle@lists.alioth.debian.org>.
Enabled features: Linux x86_64-pc-linux-gnu libsystemd serial usb libudev usbdropdir=/usr/lib/pcsc/drivers ipcdir=/var/run/pcscd configdir=/etc/reader.conf.d

Platform

![screen_version](https://user-images.githubusercontent.com/51439706/59021384-fa9c9000-884b-11e9-8cfe-3cd2d8049493.png)

log.txt

00000000 debuglog.c:289:DebugLogSetLevel() debug level=debug
00000012 debuglog.c:310:DebugLogSetCategory() Debug options: APDU
[36m00000002[0m [34mpcscdaemon.c:352:main() Force colored logs[0m
[36m00000066[0m configfile.l:285:DBGetReaderListDir() Parsing conf directory: /etc/reader.conf.d
[36m00000028[0m configfile.l:361:DBGetReaderList() Parsing conf file: /etc/reader.conf.d/libccidtwin
[36m00000036[0m configfile.l:322:DBGetReaderListDir() Skipping non regular file: ..
[36m00000006[0m configfile.l:322:DBGetReaderListDir() Skipping non regular file: .
[36m00000006[0m [34mpcscdaemon.c:662:main() pcsc-lite 1.8.23 daemon ready.[0m
[36m00003090[0m hotplug_libudev.c:297:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0002, path: /dev/bus/usb/001/001
[36m00000104[0m hotplug_libudev.c:297:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0002, path: /dev/bus/usb/001/001
[36m00000108[0m hotplug_libudev.c:297:get_driver() Looking for a driver for VID: 0x072F, PID: 0x2224, path: /dev/bus/usb/001/019
[36m00000097[0m hotplug_libudev.c:297:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0002, path: /dev/bus/usb/001/001
[36m00000107[0m hotplug_libudev.c:297:get_driver() Looking for a driver for VID: 0x8087, PID: 0x0AAA, path: /dev/bus/usb/001/005
[36m00000104[0m hotplug_libudev.c:297:get_driver() Looking for a driver for VID: 0x8087, PID: 0x0AAA, path: /dev/bus/usb/001/005
[36m00000097[0m hotplug_libudev.c:297:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0002, path: /dev/bus/usb/001/001
[36m00000103[0m hotplug_libudev.c:297:get_driver() Looking for a driver for VID: 0x05E3, PID: 0x0610, path: /dev/bus/usb/001/002
[36m00000109[0m hotplug_libudev.c:297:get_driver() Looking for a driver for VID: 0x046D, PID: 0xC050, path: /dev/bus/usb/001/004
[36m00000103[0m hotplug_libudev.c:297:get_driver() Looking for a driver for VID: 0x05E3, PID: 0x0610, path: /dev/bus/usb/001/002
[36m00000107[0m hotplug_libudev.c:297:get_driver() Looking for a driver for VID: 0x0BDA, PID: 0x8153, path: /dev/bus/usb/001/006
[36m00000102[0m hotplug_libudev.c:297:get_driver() Looking for a driver for VID: 0x05E3, PID: 0x0610, path: /dev/bus/usb/001/002
[36m00000094[0m hotplug_libudev.c:297:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0002, path: /dev/bus/usb/001/001
[36m00000102[0m hotplug_libudev.c:297:get_driver() Looking for a driver for VID: 0x13D3, PID: 0x56CB, path: /dev/bus/usb/001/003
[36m00000101[0m hotplug_libudev.c:297:get_driver() Looking for a driver for VID: 0x13D3, PID: 0x56CB, path: /dev/bus/usb/001/003
[36m00000100[0m hotplug_libudev.c:297:get_driver() Looking for a driver for VID: 0x13D3, PID: 0x56CB, path: /dev/bus/usb/001/003
[36m00000100[0m hotplug_libudev.c:297:get_driver() Looking for a driver for VID: 0x13D3, PID: 0x56CB, path: /dev/bus/usb/001/003
[36m00000155[0m hotplug_libudev.c:297:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0003, path: /dev/bus/usb/002/001
[36m02375426[0m winscard_msg_srv.c:255:ProcessEventsServer() Common channel packet arrival
[36m00000015[0m winscard_msg_srv.c:267:ProcessEventsServer() ProcessCommonChannelRequest detects: 7
[36m00000004[0m pcscdaemon.c:133:SVCServiceRunLoop() A new context thread creation is requested: 7
[36m00000050[0m winscard_svc.c:340:ContextThread() Authorized PC/SC client
[36m00000006[0m winscard_svc.c:344:ContextThread() Thread is started: dwClientID=7, threadContext @0x55b6a0eb3ce0
[36m00000009[0m winscard_svc.c:362:ContextThread() Received command: CMD_VERSION from client 7
[36m00000004[0m winscard_svc.c:374:ContextThread() Client is protocol version 4:3
[36m00000003[0m winscard_svc.c:394:ContextThread() CMD_VERSION rv=0x0 for client 7
[36m00000030[0m winscard_svc.c:362:ContextThread() Received command: ESTABLISH_CONTEXT from client 7
[36m00000007[0m winscard.c:215:SCardEstablishContext() Establishing Context: 0x42D96134
[36m00000003[0m winscard_svc.c:458:ContextThread() ESTABLISH_CONTEXT rv=0x0 for client 7
[36m00000035[0m winscard_svc.c:362:ContextThread() Received command: CMD_GET_READERS_STATE from client 7
[36m00000033[0m winscard_svc.c:362:ContextThread() Received command: CMD_WAIT_READER_STATE_CHANGE from client 7
[36m00000023[0m winscard_svc.c:362:ContextThread() Received command: CMD_STOP_WAITING_READER_STATE_CHANGE from client 7
[36m00000006[0m winscard_svc.c:439:ContextThread() CMD_STOP_WAITING_READER_STATE_CHANGE rv=0x0 for client 7
[36m00000033[0m winscard_svc.c:362:ContextThread() Received command: CMD_GET_READERS_STATE from client 7
[36m00000050[0m winscard_svc.c:362:ContextThread() Received command: CMD_GET_READERS_STATE from client 7
[36m00000025[0m winscard_svc.c:362:ContextThread() Received command: CMD_GET_READERS_STATE from client 7
[36m00000032[0m winscard_svc.c:362:ContextThread() Received command: CMD_GET_READERS_STATE from client 7
[36m00000021[0m winscard_svc.c:362:ContextThread() Received command: CMD_WAIT_READER_STATE_CHANGE from client 7
[36m01001172[0m winscard_svc.c:362:ContextThread() Received command: CMD_STOP_WAITING_READER_STATE_CHANGE from client 7
[36m00000050[0m winscard_svc.c:439:ContextThread() CMD_STOP_WAITING_READER_STATE_CHANGE rv=0x0 for client 7
[36m00000260[0m winscard_svc.c:362:ContextThread() Received command: CMD_GET_READERS_STATE from client 7
[36m00000270[0m winscard_svc.c:362:ContextThread() Received command: CMD_GET_READERS_STATE from client 7
[36m00000225[0m winscard_svc.c:362:ContextThread() Received command: CMD_WAIT_READER_STATE_CHANGE from client 7
[36m00914477[0m [34mhotplug_libudev.c:645:HPEstablishUSBNotifications() USB Device removed[0m
[36m00085808[0m winscard_svc.c:362:ContextThread() Received command: CMD_STOP_WAITING_READER_STATE_CHANGE from client 7
[36m00000046[0m winscard_svc.c:439:ContextThread() CMD_STOP_WAITING_READER_STATE_CHANGE rv=0x0 for client 7
[36m00000169[0m winscard_svc.c:362:ContextThread() Received command: CMD_GET_READERS_STATE from client 7
[36m00000169[0m winscard_svc.c:362:ContextThread() Received command: CMD_GET_READERS_STATE from client 7
[36m00000118[0m winscard_svc.c:362:ContextThread() Received command: CMD_WAIT_READER_STATE_CHANGE from client 7
[36m01001491[0m winscard_svc.c:362:ContextThread() Received command: CMD_STOP_WAITING_READER_STATE_CHANGE from client 7
[36m00000047[0m winscard_svc.c:439:ContextThread() CMD_STOP_WAITING_READER_STATE_CHANGE rv=0x0 for client 7
[36m00000231[0m winscard_svc.c:362:ContextThread() Received command: CMD_GET_READERS_STATE from client 7
[36m00000243[0m winscard_svc.c:362:ContextThread() Received command: CMD_GET_READERS_STATE from client 7
[36m00000271[0m winscard_svc.c:362:ContextThread() Received command: CMD_WAIT_READER_STATE_CHANGE from client 7
[36m01000849[0m winscard_svc.c:362:ContextThread() Received command: CMD_STOP_WAITING_READER_STATE_CHANGE from client 7
[36m00000016[0m winscard_svc.c:439:ContextThread() CMD_STOP_WAITING_READER_STATE_CHANGE rv=0x0 for client 7
[36m00000106[0m winscard_svc.c:362:ContextThread() Received command: CMD_GET_READERS_STATE from client 7
[36m00000106[0m winscard_svc.c:362:ContextThread() Received command: CMD_GET_READERS_STATE from client 7
[36m00000084[0m winscard_svc.c:362:ContextThread() Received command: CMD_WAIT_READER_STATE_CHANGE from client 7
[36m01001396[0m winscard_svc.c:362:ContextThread() Received command: CMD_STOP_WAITING_READER_STATE_CHANGE from client 7
[36m00000047[0m winscard_svc.c:439:ContextThread() CMD_STOP_WAITING_READER_STATE_CHANGE rv=0x0 for client 7
[36m00000186[0m winscard_svc.c:362:ContextThread() Received command: CMD_GET_READERS_STATE from client 7
[36m00000204[0m winscard_svc.c:362:ContextThread() Received command: CMD_GET_READERS_STATE from client 7
[36m00000156[0m winscard_svc.c:362:ContextThread() Received command: CMD_WAIT_READER_STATE_CHANGE from client 7
[36m00022779[0m [34mhotplug_libudev.c:651:HPEstablishUSBNotifications() USB Device add[0m
[36m00000186[0m hotplug_libudev.c:297:get_driver() Looking for a driver for VID: 0x072F, PID: 0x2224, path: /dev/bus/usb/001/020
[36m00978506[0m winscard_svc.c:362:ContextThread() Received command: CMD_STOP_WAITING_READER_STATE_CHANGE from client 7
[36m00000016[0m winscard_svc.c:439:ContextThread() CMD_STOP_WAITING_READER_STATE_CHANGE rv=0x0 for client 7
[36m00000124[0m winscard_svc.c:362:ContextThread() Received command: CMD_GET_READERS_STATE from client 7
[36m00000065[0m winscard_svc.c:362:ContextThread() Received command: CMD_GET_READERS_STATE from client 7
[36m00000031[0m winscard_svc.c:362:ContextThread() Received command: CMD_WAIT_READER_STATE_CHANGE from client 7
[36m01001355[0m winscard_svc.c:362:ContextThread() Received command: CMD_STOP_WAITING_READER_STATE_CHANGE from client 7
[36m00000046[0m winscard_svc.c:439:ContextThread() CMD_STOP_WAITING_READER_STATE_CHANGE rv=0x0 for client 7
[36m00000250[0m winscard_svc.c:362:ContextThread() Received command: CMD_GET_READERS_STATE from client 7
[36m00000256[0m winscard_svc.c:362:ContextThread() Received command: CMD_GET_READERS_STATE from client 7
[36m00000222[0m winscard_svc.c:362:ContextThread() Received command: CMD_WAIT_READER_STATE_CHANGE from client 7
[36m01001555[0m winscard_svc.c:362:ContextThread() Received command: CMD_STOP_WAITING_READER_STATE_CHANGE from client 7
[36m00000017[0m winscard_svc.c:439:ContextThread() CMD_STOP_WAITING_READER_STATE_CHANGE rv=0x0 for client 7
[36m00000068[0m winscard_svc.c:362:ContextThread() Received command: CMD_GET_READERS_STATE from client 7
[36m00000058[0m winscard_svc.c:362:ContextThread() Received command: CMD_GET_READERS_STATE from client 7
[36m00000027[0m winscard_svc.c:362:ContextThread() Received command: CMD_WAIT_READER_STATE_CHANGE from client 7
[36m01000389[0m winscard_svc.c:362:ContextThread() Received command: CMD_STOP_WAITING_READER_STATE_CHANGE from client 7
[36m00000040[0m winscard_svc.c:439:ContextThread() CMD_STOP_WAITING_READER_STATE_CHANGE rv=0x0 for client 7
[36m00000076[0m winscard_svc.c:362:ContextThread() Received command: CMD_GET_READERS_STATE from client 7
[36m00000224[0m winscard_svc.c:362:ContextThread() Received command: CMD_GET_READERS_STATE from client 7
[36m00000133[0m winscard_svc.c:362:ContextThread() Received command: CMD_WAIT_READER_STATE_CHANGE from client 7
[36m01001418[0m winscard_svc.c:362:ContextThread() Received command: CMD_STOP_WAITING_READER_STATE_CHANGE from client 7
[36m00000017[0m winscard_svc.c:439:ContextThread() CMD_STOP_WAITING_READER_STATE_CHANGE rv=0x0 for client 7
[36m00000115[0m winscard_svc.c:362:ContextThread() Received command: CMD_GET_READERS_STATE from client 7
[36m00000065[0m winscard_svc.c:362:ContextThread() Received command: CMD_GET_READERS_STATE from client 7
[36m00000097[0m winscard_svc.c:362:ContextThread() Received command: CMD_WAIT_READER_STATE_CHANGE from client 7
[36m01001213[0m winscard_svc.c:362:ContextThread() Received command: CMD_STOP_WAITING_READER_STATE_CHANGE from client 7
[36m00000047[0m winscard_svc.c:439:ContextThread() CMD_STOP_WAITING_READER_STATE_CHANGE rv=0x0 for client 7
[36m00000246[0m winscard_svc.c:362:ContextThread() Received command: CMD_GET_READERS_STATE from client 7
[36m00000229[0m winscard_svc.c:362:ContextThread() Received command: CMD_GET_READERS_STATE from client 7
[36m00000182[0m winscard_svc.c:362:ContextThread() Received command: CMD_WAIT_READER_STATE_CHANGE from client 7
[36m01001038[0m winscard_svc.c:362:ContextThread() Received command: CMD_STOP_WAITING_READER_STATE_CHANGE from client 7
[36m00000015[0m winscard_svc.c:439:ContextThread() CMD_STOP_WAITING_READER_STATE_CHANGE rv=0x0 for client 7
[36m00000104[0m winscard_svc.c:362:ContextThread() Received command: CMD_GET_READERS_STATE from client 7
[36m00000063[0m winscard_svc.c:362:ContextThread() Received command: CMD_GET_READERS_STATE from client 7
[36m00000093[0m winscard_svc.c:362:ContextThread() Received command: CMD_WAIT_READER_STATE_CHANGE from client 7
[36m01001193[0m winscard_svc.c:362:ContextThread() Received command: CMD_STOP_WAITING_READER_STATE_CHANGE from client 7
[36m00000041[0m winscard_svc.c:439:ContextThread() CMD_STOP_WAITING_READER_STATE_CHANGE rv=0x0 for client 7
[36m00000209[0m winscard_svc.c:362:ContextThread() Received command: CMD_GET_READERS_STATE from client 7
[36m00000207[0m winscard_svc.c:362:ContextThread() Received command: CMD_GET_READERS_STATE from client 7
[36m00000231[0m winscard_svc.c:362:ContextThread() Received command: CMD_WAIT_READER_STATE_CHANGE from client 7

gdb pcscd =>

GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from pcscd...Reading symbols from /usr/lib/debug/.build-id/24/5e47e40de4e0b182b0999933c8831eeaa5e365.debug...done.
done.
(gdb) 
(gdb) 
(gdb) 
(gdb)

**Comment by LudovicRousseau** [comment]
Your reader "ID 072f:2224 Advanced Card Systems, Ltd ACR1281 1S Dual Reader" is not supported by the CCID driver.

See https://ccid.apdu.fr/#CCID_compliant

**Comment by Demso-alex** [comment]
Thank you !
but I find it weird because I used the RFID reader on a raspberry! And the program works!
It's normal ?

**Comment by Demso-alex** [comment]
I just did the same thing with raspberry.
The reader is not supported but it still works.
You know why ?

![image](https://user-images.githubusercontent.com/51439706/59023965-28d09e80-8851-11e9-9298-091cf25ae5e8.png)

**Comment by LudovicRousseau** [comment]
Maybe you installed another driver? A driver from ACS like libacsccid1?

**Comment by Demso-alex** [comment]
Yes ! it's work with libacsccid1 !! 
thank you ;)

have a good day
