### ISSUE TITLE
Using multiple usb readers reduce read/write speeds

### ISSUE THREAD

**Issue by maysam-shirazi** [LudovicRousseau/PCSC#67]
I'm using ubuntu 16 with Java 1.8 to run my app to read/write some smart cards with GemPC usb readers. I found that everything is ok when I'm using a single reader, so when I add new reader two read/write two cards synchronously duration is doubled. it seams that usb readers do not work parallel and APDU commands are in one queue for all of usb readers! I test it in Microsoft WIN7 so it's working(parallel process for multiple usb readers).
I'll appreciate for any help.

**Comment by LudovicRousseau** [comment]
I think it is a bug/limitation of the Java PC/SC API.

**Comment by LudovicRousseau** [comment]
You may want to use https://github.com/intarsys/smartcard-io instead of the implementation from Oracle.
