### ISSUE TITLE
HID omikey smart card reader issue

### ISSUE THREAD

**Issue by itsme300** [LudovicRousseau/PCSC#69]
~$ sudo LIBCCID_ifdLogLevel=0x000F pcscd --foreground --debug --apdu --color | tee log.txt
00000000 debuglog.c:291:DebugLogSetLevel() debug level=debug
00000123 debuglog.c:312:DebugLogSetCategory() Debug options: APDU
00000007 pcscdaemon.c:268:main() Force colored logs
00000049 configfile.l:283:DBGetReaderListDir() Parsing conf directory: /etc/reader.conf.d
00000016 configfile.l:317:DBGetReaderListDir() Skipping non regular file: ..
00000005 configfile.l:317:DBGetReaderListDir() Skipping non regular file: .
00000005 configfile.l:355:DBGetReaderList() Parsing conf file: /etc/reader.conf.d/libccidtwin
00000049 pcscdaemon.c:569:main() pcsc-lite 1.8.14 daemon ready.
00005702 hotplug_libudev.c:296:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0002, path: /dev/bus/usb/001/001
00000208 hotplug_libudev.c:296:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0002, path: /dev/bus/usb/001/001
00000349 hotplug_libudev.c:296:get_driver() Looking for a driver for VID: 0x80EE, PID: 0x0021, path: /dev/bus/usb/001/002
00000226 hotplug_libudev.c:296:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0002, path: /dev/bus/usb/001/001
00000311 hotplug_libudev.c:296:get_driver() Looking for a driver for VID: 0x076B, PID: 0x3031, path: /dev/bus/usb/001/010
00000033 hotplug_libudev.c:435:HPAddDevice() Adding USB device: OMNIKEY CardMan (076B:3031) 3031
00000092 readerfactory.c:1012:RFInitializeReader() Attempting startup of OMNIKEY CardMan (076B:3031) 3031 [OMNIKEY 3x21 Smart Card Reader] 00 00 using /usr/lib/pcsc/drivers/ifdokccid_linux_x86_64-v4.2.8.bundle/Contents/Linux/ifdokccid.so
00000287 readerfactory.c:897:RFBindFunctions() Loading IFD Handler 3.0
[HID Global] HID Global OMNIKEY CCID driver x86_64 v4.2.8 eusupport@hidglobal.com
00003542 readerfactory.c:1043:RFInitializeReader() Open Port 0x200000 Failed (usb:076b/3031:libudev:0:/dev/bus/usb/001/010)
00000029 readerfactory.c:335:RFAddReader() OMNIKEY CardMan (076B:3031) 3031 [OMNIKEY 3x21 Smart Card Reader] init failed.
00000009 readerfactory.c:558:RFRemoveReader() UnrefReader() count was: 1
00000005 readerfactory.c:1063:RFUnInitializeReader() Attempting shutdown of OMNIKEY CardMan (076B:3031) 3031 [OMNIKEY 3x21 Smart Card Reader] 00 00.
00000004 readerfactory.c:934:RFUnloadReader() Unloading reader driver.
00000051 hotplug_libudev.c:507:HPAddDevice() Failed adding USB device: OMNIKEY CardMan (076B:3031) 3031
00000278 hotplug_libudev.c:296:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0003, path: /dev/bus/usb/002/001

**Comment by LudovicRousseau** [comment]
You are using the HID proprietary driver.
As indicated in the logs contact eusupport@hidglobal.com
