### ISSUE TITLE
How to always load my Cryto token kit driver using PCSC?

### ISSUE THREAD

**Issue by RiteshAdobe** [LudovicRousseau/PCSC#74]
Hi,

Is it possible to load a pre-defined CrytoTokenKit (CTK) driver using PCSC ? 

The reason i am asking is because if it is possible, i will be able to load my CTK driver (using pcsc) which will in-turn communicate with my HSM to fetch crts/keys ,because we don't have any physical smart card.

Looks like CTK is always loaded upon a "smart card insertion event" . Since we don't have that, i was wondering if we could get PCSC to always load my CTK driver . 

If such a thing is possible, there will not be any need to actually "insert a smart card / generate any usb based event".

Appreciate your reply.

**Comment by LudovicRousseau** [comment]
CrytoTokenKit is a macOS technology. pcsc-lite does NOT support macOS. Apple has its own version of PC/SC.

And you already know how to solve your problem. We discussed already.
