### ISSUE TITLE
Issue with ACR122U + Low voltage?

### ISSUE THREAD

**Issue by nathan-ny** [LudovicRousseau/PCSC#77]
Hello,

I am having a problem with my ACS ACR122U. I noticed that the problem
occurs more often when I use a longer cable connected to the power supply.
What is weird for me is that <code>lsusb</code> shows me that the card reader
is connected to the USB port, but <code>systemctl status pcscd</code> give me
some error messages.

I noticed too that if I restart pcscd.service the card reader works for random
time (sometimes not) and then stops again.

If I change the power supply cable to a short one (still same power supply), reboot
system and disconnect/reconnect the card reader to the same USB port, then it works.
Also, sometimes, it works without need to disconnect/reconnect.

Output from systemctl status pcscd.service:

● pcscd.service - PC/SC Smart Card Daemon
   Loaded: loaded (/lib/systemd/system/pcscd.service; indirect; vendor preset: enabled)
   Active: active (running) since Thu 2020-06-04 08:52:53 CEST; 59s ago
 Main PID: 629 (pcscd)
   CGroup: /system.slice/pcscd.service
           └─629 /usr/sbin/pcscd --foreground --auto-exit

Jun 04 08:52:53 stechuhr systemd[1]: Started PC/SC Smart Card Daemon.
Jun 04 08:52:54 stechuhr pcscd[629]: 00000000 ccid_usb.c:836:ReadUSB() read failed (1/4): -7 LIBUSB_ERROR_TIMEOUT
Jun 04 08:52:54 stechuhr pcscd[629]: 00141122 ccid_usb.c:836:ReadUSB() read failed (1/4): -7 LIBUSB_ERROR_TIMEOUT
Jun 04 08:52:54 stechuhr pcscd[629]: 00000065 ifdhandler.c:195:CreateChannelByNameOrChannel() failed
Jun 04 08:52:54 stechuhr pcscd[629]: 00001005 readerfactory.c:1110:RFInitializeReader() Open Port 0x200000 Failed (usb:072f/2200:libudev:0:/dev/bus/usb/001/004)
Jun 04 08:52:54 stechuhr pcscd[629]: 00000040 readerfactory.c:375:RFAddReader() ACS ACR122U PICC Interface init failed.
Jun 04 08:52:54 stechuhr pcscd[629]: 00000214 hotplug_libudev.c:520:HPAddDevice() Failed adding USB device: ACS ACR122U PICC Interface

Output from lsusb:

Bus 001 Device 004: ID 072f:2200 Advanced Card Systems, Ltd ACR122U
Bus 001 Device 005: ID 0424:7800 Standard Microsystems Corp. 
Bus 001 Device 003: ID 0424:2514 Standard Microsystems Corp. USB 2.0 Hub
Bus 001 Device 002: ID 0424:2514 Standard Microsystems Corp. USB 2.0 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

System info:
pcsc-lite version 1.8.20.
Copyright (C) 1999-2002 by David Corcoran <corcoran@musclecard.com>.
Copyright (C) 2001-2015 by Ludovic Rousseau <ludovic.rousseau@free.fr>.
Copyright (C) 2003-2004 by Damien Sauveron <sauveron@labri.fr>.
Report bugs to <pcsclite-muscle@lists.alioth.debian.org>.
Enabled features: Linux arm-unknown-linux-gnueabihf serial usb libudev usbdropdir=/usr/lib/pcsc/drivers ipcdir=/var/run/pcscd configdir=/etc/reader.conf.d

pcsc-tools version 1.4.27-1+b4

libusb-1.0-0: 2:1.0.21-1

Raspberry Pi 3 model B+
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

Card Reader:
ACS ACR122U-A9
S/N RR171-414898

Here is the log output:

00000000 debuglog.c:289:DebugLogSetLevel() debug level=debug
00000271 debuglog.c:310:DebugLogSetCategory() Debug options: APDU
00000021 pcscdaemon.c:351:main() Force colored logs
00000102 utils.c:82:GetDaemonPid() Can't open /var/run/pcscd/pcscd.pid: No such file or directory
00000386 configfile.l:282:DBGetReaderListDir() Parsing conf directory: /etc/reader.conf.d
00000072 configfile.l:319:DBGetReaderListDir() Skipping non regular file: ..
00000019 configfile.l:358:DBGetReaderList() Parsing conf file: /etc/reader.conf.d/libccidtwin
00000169 configfile.l:319:DBGetReaderListDir() Skipping non regular file: .
00000035 pcscdaemon.c:655:main() pcsc-lite 1.8.20 daemon ready.
00018495 hotplug_libudev.c:294:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0002, path: /dev/bus/usb/001/001
00000957 hotplug_libudev.c:294:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0002, path: /dev/bus/usb/001/001
00000930 hotplug_libudev.c:294:get_driver() Looking for a driver for VID: 0x0424, PID: 0x2514, path: /dev/bus/usb/001/002
00000965 hotplug_libudev.c:294:get_driver() Looking for a driver for VID: 0x0424, PID: 0x2514, path: /dev/bus/usb/001/003
00001039 hotplug_libudev.c:294:get_driver() Looking for a driver for VID: 0x0424, PID: 0x7800, path: /dev/bus/usb/001/005
00000972 hotplug_libudev.c:294:get_driver() Looking for a driver for VID: 0x0424, PID: 0x2514, path: /dev/bus/usb/001/003
00000915 hotplug_libudev.c:294:get_driver() Looking for a driver for VID: 0x0424, PID: 0x2514, path: /dev/bus/usb/001/002
00000867 hotplug_libudev.c:294:get_driver() Looking for a driver for VID: 0x072F, PID: 0x2200, path: /dev/bus/usb/001/004
00000035 hotplug_libudev.c:433:HPAddDevice() Adding USB device: ACS ACR122U PICC Interface
00000242 readerfactory.c:1079:RFInitializeReader() Attempting startup of ACS ACR122U PICC Interface 00 00 using /usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Linux/libccid.so
00001178 readerfactory.c:954:RFBindFunctions() Loading IFD Handler 3.0
00000162 ifdhandler.c:1961:init_driver() Driver version: 1.4.26
00005789 ifdhandler.c:1978:init_driver() LogLevel: 0x0003
00000036 ifdhandler.c:1989:init_driver() DriverOptions: 0x0000
00001008 ifdhandler.c:2002:init_driver() LogLevel from LIBCCID_ifdLogLevel: 0x000F
00000024 ifdhandler.c:111:CreateChannelByNameOrChannel() Lun: 0, device: usb:072f/2200:libudev:0:/dev/bus/usb/001/004
00000021 ccid_usb.c:237:OpenUSBByName() Reader index: 0, Device: usb:072f/2200:libudev:0:/dev/bus/usb/001/004
00000045 ccid_usb.c:269:OpenUSBByName() interface_number: 0
00000017 ccid_usb.c:270:OpenUSBByName() usb bus/device: 1/4
00000017 ccid_usb.c:287:OpenUSBByName() Using: /usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Info.plist
00005883 ccid_usb.c:305:OpenUSBByName() ifdManufacturerString: Ludovic Rousseau (ludovic.rousseau@free.fr)
00000037 ccid_usb.c:306:OpenUSBByName() ifdProductString: Generic CCID driver
00000020 ccid_usb.c:307:OpenUSBByName() Copyright: This driver is protected by terms of the GNU Lesser General Public License version 2.1, or (at your option) any later version.
00012243 ccid_usb.c:391:OpenUSBByName() Try device: 1/4
00000023 ccid_usb.c:401:OpenUSBByName() vid/pid : 072F/2200
00000007 ccid_usb.c:448:OpenUSBByName() Checking device: 1/4
00000008 ccid_usb.c:519:OpenUSBByName() Trying to open USB bus/device: 1/4
00090483 ccid_usb.c:621:OpenUSBByName() Found Vendor/Product: 072F/2200 (ACS ACR122U PICC Interface)
00000038 ccid_usb.c:623:OpenUSBByName() Using USB bus/device: 1/4
00000020 ccid_usb.c:680:OpenUSBByName() bNumDataRatesSupported is 0
00004697 ccid_usb.c:1244:InterruptRead() before (0)
00100144 ccid_usb.c:1290:InterruptRead() after (0) (2)
00000054 -> 000000 65 00 00 00 00 00 00 00 00 00 
00002921 <- 000000 81 00 00 00 00 00 01 02 81 00 
00000041 -> 000000 65 00 00 00 00 00 01 00 00 00 
00100315 ccid_usb.c:836:ReadUSB() read failed (1/4): -7 LIBUSB_ERROR_TIMEOUT
00000066 -> 000000 65 00 00 00 00 00 02 00 00 00 
00040450 <- 000000 81 00 00 00 00 00 02 02 81 00 
00000040 ifdhandler.c:382:IFDHGetCapabilities() tag: 0xFB3, usb:072f/2200:libudev:0:/dev/bus/usb/001/004 (lun: 0)
00000019 readerfactory.c:395:RFAddReader() Using the reader polling thread
00000018 ifdhandler.c:1821:IFDHICCPresence() usb:072f/2200:libudev:0:/dev/bus/usb/001/004 (lun: 0)
00000028 -> 000000 65 00 00 00 00 00 03 00 00 00 
00000541 <- 000000 81 00 00 00 00 00 00 02 81 00 
00000021 ccid_usb.c:858:ReadUSB() Duplicate frame detected
03000181 ccid_usb.c:836:ReadUSB() read failed (1/4): -7 LIBUSB_ERROR_TIMEOUT
00000051 ifdwrapper.c:369:IFDStatusICC() Card not transacted: 612
00000020 eventhandler.c:230:EHSpawnEventHandler() Initial Check Failed on ACS ACR122U PICC Interface 00 00
00000016 readerfactory.c:401:RFAddReader() ACS ACR122U PICC Interface init failed.
00000020 readerfactory.c:608:RFRemoveReader() UnrefReader() count was: 1
00000017 readerfactory.c:1130:RFUnInitializeReader() Attempting shutdown of ACS ACR122U PICC Interface 00 00.
00000020 ifdhandler.c:285:IFDHCloseChannel() usb:072f/2200:libudev:0:/dev/bus/usb/001/004 (lun: 0)
00000033 -> 000000 63 00 00 00 00 00 04 00 00 00 
00000475 <- 000000 81 00 00 00 00 00 01 02 81 00 
00000023 ccid_usb.c:858:ReadUSB() Duplicate frame detected
03000158 ccid_usb.c:836:ReadUSB() read failed (1/4): -7 LIBUSB_ERROR_TIMEOUT
00000052 ccid_usb.c:879:CloseUSB() Closing USB device: 1/4
00000023 ccid_usb.c:889:CloseUSB() Last slot closed. Release resources
00000660 ccid_usb.c:189:close_libusb_if_needed() libusb_exit
00000556 readerfactory.c:991:RFUnloadReader() Unloading reader driver.
00000218 hotplug_libudev.c:520:HPAddDevice() Failed adding USB device: ACS ACR122U PICC Interface
00001369 hotplug_libudev.c:294:get_driver() Looking for a driver for VID: 0x0424, PID: 0x2514, path: /dev/bus/usb/001/002

What/where could be the problem?

Many thanks in advance!

**Comment by LudovicRousseau** [comment]
What do you call a power supply cable?

**Comment by nathan-ny** [comment]
By power supply cable I mean the USB cable that it connected to the power supply (5v/3A) and to raspberry

**Comment by LudovicRousseau** [comment]
So you already know the answer. It is a power supply issue.

If the reader works fine when connected to a "normal" PC then the problem is not with the reader or the driver.

**Comment by nathan-ny** [comment]
I just want to point that the same system, but with another ACR122U (older ones, S/N RR171-048439), work fines. Could it be something on the firmware? You know a way to check it?
Thanks!
