### ISSUE TITLE
epass2003 auto redirection issue through pcscd 

### ISSUE THREAD

**Issue by ganeshjkale** [LudovicRousseau/PCSC#83]
pcscd  --version
pcsc-lite version 1.8.23.
Copyright (C) 1999-2002 by David Corcoran <corcoran@musclecard.com>.
Copyright (C) 2001-2015 by Ludovic Rousseau <ludovic.rousseau@free.fr>.
Copyright (C) 2003-2004 by Damien Sauveron <sauveron@labri.fr>.
Report bugs to <pcsclite-muscle@lists.alioth.debian.org>.
Enabled features: Linux x86_64-pc-linux-gnu libsystemd serial usb libudev usbdropdir=/usr/lib/pcsc/drivers ipcdir=/var/run/pcscd configdir=/etc/reader.conf.d

Client OS :- ubuntu 18.04_x64
Server OS :- windows 2016 server 

Scenario:-
1:-Trying to redirect auto epass2003 token through freerdp-2.2.0 
2:-token is redirected for 1 second and disconnected 
3:-step 2 repeats infinite times.

Note:-
1:-Issue reported to freerdp on github and they are suspecting driver issue.(can you help or guide on this)
https://github.com/FreeRDP/FreeRDP/issues/6444

Attached log file :- 
[log.txt](https://github.com/LudovicRousseau/PCSC/files/5117387/log.txt)

**Comment by LudovicRousseau** [comment]
I don't find any error in the log you sent.

**Comment by ganeshjkale** [comment]
@LudovicRousseau does this below log can create problem in usb redirection:- 

> ^[[36m00000031^[[0m ^[[01;31mifdhandler.c:150:CreateChannelByNameOrChannel() failed^[[0m
> ^[[36m00000008^[[0m ^[[01;31mreaderfactory.c:1106:RFInitializeReader() Open Port 0x200000 Failed (usb:096e/080a:libudev:0:/dev/bus/usb/001/011)^[[0m
> ^[[36m00000004^[[0m ^[[35mreaderfactory.c:376:RFAddReader() FT ePass2003Auto init failed.^[[0m

**Comment by LudovicRousseau** [comment]
No. Your reader is detected correctly on GNU/Linux.
