### ISSUE TITLE
Does someone who knows or build pics lite lib(static and dynamic) on android? 

### ISSUE THREAD

**Issue by FeitianSmartcardReader** [LudovicRousseau/PCSC#9]
Hi guys 

Hope using PCSC LIte and ccid under android, does someone who knows where can find useful resource? 

Thanks.

**Comment by LudovicRousseau** [comment]
Have a look at the seek-for-android project https://seek-for-android.github.io/

**Comment by FeitianSmartcardReader** [comment]
Saw it already and solve my problem. Thanks Sent from Ben's phone  

            On 04/29/2016 00:49, Ludovic Rousseau wrote:Have a look at the seek-for-android project https://seek-for-android.github.io/
