### ISSUE TITLE
Yubikey troubles

### ISSUE THREAD

**Issue by dangoncalves** [LudovicRousseau/PCSC#91]
Hi,

I'm experiencing some troubles with a Yubikey while changing the pin code or uploading a GPG key and I suspect pcscd to be the root cause.

Here is the log from the pcscd daemon
```
déc. 22 09:34:36 P-LYO-AYENT pcscd[7310]: 00000000 ifdhandler.c:150:CreateChannelByNameOrChannel() failed
déc. 22 09:34:36 P-LYO-AYENT pcscd[7310]: 00000100 readerfactory.c:1105:RFInitializeReader() Open Port 0x200000 Failed (usb:1050/0407:libudev:0:/dev/bus/usb/001/006)
déc. 22 09:34:36 P-LYO-AYENT pcscd[7310]: 00000003 readerfactory.c:376:RFAddReader() Yubico YubiKey OTP+FIDO+CCID init failed.
déc. 22 09:34:36 P-LYO-AYENT pcscd[7310]: 00004789 ifdhandler.c:150:CreateChannelByNameOrChannel() failed
déc. 22 09:34:36 P-LYO-AYENT pcscd[7310]: 00000011 readerfactory.c:1105:RFInitializeReader() Open Port 0x200000 Failed (usb:1050/0407:libudev:1:/dev/bus/usb/001/006)
déc. 22 09:34:36 P-LYO-AYENT pcscd[7310]: 00000002 readerfactory.c:376:RFAddReader() Yubico YubiKey OTP+FIDO+CCID init failed.
déc. 22 09:34:36 P-LYO-AYENT pcscd[7310]: 00112177 ifdhandler.c:150:CreateChannelByNameOrChannel() failed
```

The full log  can be found [here](https://github.com/LudovicRousseau/PCSC/files/5728749/log.txt)

What I tried to do:
 - Plug the Yubikey
 - Change the Pin
 - Unplug the Yubikey

Is pcscd the root cause of my problems, as I suspect?

Thanks.

**Comment by LudovicRousseau** [comment]
pcscd is **not** your problem.
To check your device is working correct see https://ludovicrousseau.blogspot.com/2014/03/level-1-smart-card-support-on-gnulinux.html

In your case the problem is this APDU command:
```
00000022 APDU: 00 24 00 80 10 31 32 33 34 35 36 FF FF 36 35 34 33 32 31 FF FF 
00000045 SW: 69 83 
```
69 83 is the error code for "Authentication method blocked."

**Comment by dangoncalves** [comment]
OK. Many thanks for your quick answer.
