### ISSUE TITLE
Releases consistency and primary source

### ISSUE THREAD

**Issue by Jakuje** [LudovicRousseau/PCSC#96]
We are using https://release-monitoring.org/project/2611/  to keep track of new releases. At this moment, it is plugged into the (old?) debian repository and was matching the old regex of tags that was valid for couple of years but the latest release has different pattern:

https://salsa.debian.org/rousseau/PCSC/-/tags

I already noticed this with ccid, which I changed to follow github repository (which is much simpler than parsing the custom code in https://pcsclite.apdu.fr/files/ ), but this one for some reason does not show the latest version on the right column (while the tags look fine).

I am filling this issue mostly to ask if using github repository as a source for the latest version is fine (I am downloading the files from the apdu.fr anyway) and whether there is something wrong with the releases block on the right.

**Comment by LudovicRousseau** [comment]
I forgot to create a new release on github. Sorry.
Release 1.9.1 is now listed on the github page.

I have a question: what is the best tag format? "pcsc-1.9.1" or just "1.9.1"?

**Comment by LudovicRousseau** [comment]
Do you know why the version 1.9.1 is not listed at https://release-monitoring.org/project/2611/ ?

**Comment by Jakuje** [comment]
Thanks. All the previous tags are in the format 1.9.1 and I think it is fine. I think more important is to keep it consistent with the previous releases. What is different is the message content "pcsc-1.9.0" vs "Release 1.9.1".

> Do you know why the version 1.9.1 is not listed at https://release-monitoring.org/project/2611/ ?

Because it follows https://salsa.debian.org/rousseau/PCSC/-/tags where the above changed.

**Comment by Jakuje** [comment]
I can simply change it to follow the github tags/releases if you do not plan to move the repository somewhere else before next release ;)

**Comment by LudovicRousseau** [comment]
The pcsc-lite projects on salsa.debian.org and github.com shoudl be in sync. I do not plan to move the repository somewhere else.
I did not know that the _message_ in the tag commit was also important.

**Comment by Jakuje** [comment]
only for this specific tool. I will change it to use github, which is easier. Thanks.
