### ISSUE TITLE
Connect 54 tokens in a usb hub

### ISSUE THREAD

**Issue by angelsantillana94** [LudovicRousseau/PCSC#97]
Hello,

I need to connect 54 crypto token to a server.

```
[root@host ~]# cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)

[root@host ~]# uname -a
Linux host.mynetwork.com 5.4.103-1.el7.elrepo.x86_64 #1 SMP Sun Mar 7 08:15:14 EST 2021 x86_64 x86_64 x86_64 GNU/Linux

```

```
[root@host ~]# rpm -qa | grep pcsc | sort
pcsc-lite-1.8.8-8.el7.x86_64
pcsc-lite-ccid-1.4.10-15.el7.x86_64
pcsc-lite-devel-1.8.8-8.el7.x86_64
pcsc-lite-libs-1.8.8-8.el7.x86_64
pcsc-perl-1.4.14-2.el7.x86_64
pcsc-tools-1.4.25-1.el7.x86_64
```

The token model is "Feitian Technologies, Inc. ePass2003". Currently I am testing with the following hub:

https://www.batterfly.com/shop/es/cambrionix/cambrionix-syncpad54

Do you think this is possible? What problem can I find with this configuration? what is your recommendation in this regard?

Thank you very much.

**Comment by LudovicRousseau** [comment]
https://ludovicrousseau.blogspot.com/2021/03/a-lot-of-readers-connected-to-computer.html

**Comment by LudovicRousseau** [comment]
And also https://ludovicrousseau.blogspot.com/2021/03/accessing-lot-of-smart-cards.html
